### ISSUE TITLE
Syntax highlighting assumes all errors are in the same editor

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#1]
This leads to buggy highlighting of e.g. arity mismatches when a function at the REPL calls a function in definitions.  All of the *-ui.js modules need to take a dictionary of editors, rather than just the most recently-run editor.

**Comment by schanzer** [comment]
This appears to be fixed on horizon.

**Comment by blerner** [comment]
I think this is fixed on CPO/master, too. Closing.
