### ISSUE TITLE
Extra padding around triangles?

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#104]
When I draw `frame(triangle(40, "solid", "black"))`, there's no gap below the bottom of the triangle.  But if I do `frame(scale(4, triangle(10, "solid", "black")))`, I get a gap below the bottom.

Full example:
```
PX-PER-UNIT = 10
ARROW-COLOR = "black"

fun arrow(theta, magnitude):
  scaled-arrow = beside(
    scale(magnitude, rectangle(PX-PER-UNIT, PX-PER-UNIT / 3, "solid", ARROW-COLOR)),
    scale((magnitude / 3) + num-sqrt(magnitude), rotate(270, scale(0.25, triangle(4 * PX-PER-UNIT, "solid", ARROW-COLOR)))))
  rotate(theta, scaled-arrow)
end
```
try `arrow(0, 1)`, `arrow(0, 10)`, `arrow(0, 50)` to see what happens with this gap.

@schanzer , @jpolitz , might this have to do with the fixes made to make polygons a bit crisper?

**Comment by schanzer** [comment]
Actually, the new work made this gap a whole lot better:
[Before crispifying](http://197.wescheme.appspot.com/view?publicId=P4p1YdH05p)
[After crispifying](http://www.wescheme.org/view?publicId=P4p1YdH05p)

The issue here is browser anti-aliasing: a black diagonal line is going to have grayish pixels added to it, to smooth it out. Some browsers claim to have an option to turn this off...but when I last tried (5 months ago) it didn't work. 

For extra fun, try changing the triangle's style from `"solid"` to `"outline"`.

**Comment by blerner** [comment]
My initial issue is with the horizontal line at the base of the triangle, so not concerned with any anti-aliased angled lines. I'm all too aware of how screwy anti-aliasing can get :-)

**Comment by schanzer** [comment]
I'm trying (arrow 0 50) in WeScheme, and I'm not seeing any line. But when I fire it up in pyret-dev and CPO, I see a big one. It looks like the crispy changes have made it to either of those instances. Am I looking at the right instance here?

**Comment by blerner** [comment]
Yes, pyret-dev is the one to be looking at right now.

Ok, this is very weird.  If you use `frame` to see the components of this arrow, it looks totally weird: most of the gap is coming from the rectangle itself, not the triangle.  If I replace
```
scale(magnitude, rectangle(PX-PER-UNIT, PX-PER-UNIT / 3, "solid", ARROW-COLOR))
```
with
```
rectangle(magnitude * PX-PER-UNIT, magnitude * (PX-PER-UNIT / 3), "solid", ARROW-COLOR)
```
the gap (almost) completely goes away.  So, maybe this bug should be, extra padding around scaled rectangles?  I'm very confused...

**Comment by blerner** [comment]
It definitely seems like it's a padding issue somewhere: if I make an overly-big triangle and then scale it down, I get less of a gap.  If I make a rectangle of the scaled-up size, rather than scaling up a smaller rectangle, I get less of a gap.

**Comment by schanzer** [comment]
Ah, now I see - and yes, it's related to the sub-pixel rendering issue. This is going to take some time to digest, since tightening the vertices to fix Shriram's blurred line bug also caused a fractional pixel of empty space. When an image is amplified, that fraction becomes a problem. *sigh* On my list, but almost certainly no quick fix...

**Comment by schanzer** [comment]
Maybe it's the sleep-deprivation, but I'm not able to recreate this on WeScheme. The `frame` example in the original post does not show a gap at the bottom of the triangle at all, and putting a frame around a scaled rectangle also leaves no gap. 

What am I missing from here?
http://www.wescheme.org/view?publicId=yTbMiNHfrT

**Comment by blerner** [comment]
No, that looks reasonable...but on Pyret it manifestly doesn't.

VERY interestingly, if I put a frame around the rectangle alone, the gap "disappears", though then the 1-px frame gets scaled and thickened, so the proportions of the arrow are all wrong.  It seems like the problem is more likely on the rectangle now, rather than the triangle.  Can you look at rectangles in WeScheme and Pyret at the moment, and see if we lost a bit of your image updates when porting them?

**Comment by schanzer** [comment]
```square(300, "solid","red")
scale(30, square(10, "solid","red"))``` 
Is a much simpler test case (might be better to replace the code in the OP), which I can similarly reproduce for `triangle`. I don't see any difference whatsoever between CPO and WeScheme implementations of either of those functions!

The external-facing API passes the square-length into the image library, which passes it to `RectangleImage` the same way in both codebases. `RectangleImage` itself is the same in both codebases, as is the `render` function. I'm truly stumped here.

**Comment by blerner** [comment]
So in CPO when I stepped through it, the 300-px square image produces vertices of `{0.5, 299.5}, {299.5, 299.5}, {0.5, 0.5}, {0.5, 299.5}`, while the 10-px square image produces vertices of `{0.5, 9.5}, {299.5, 9.5}, {0.5, 0.5}, {0.5, 9.5}`.  Then that half-pixel offset gets magnified by 30x from the scaling, and you get a gap.

In CPO, in BaseImage.prototype.render, I see
```
ctx.moveTo(x+vertices[0].x, y+vertices[0].y);
```
But in WeScheme, in the equivalent function, I see
```
        b.moveTo(c + this.vertices[0].x, j + this.vertices[0].y);
```
Those are the unadjusted vertices -- the code created a new `vertices` array (by mapping over `this.vertices`) and then ignored it.  So the moved positions are not on half-pixel boundaries, and so the picture is drawn the right size.

Now given that that's the case, I have no idea how WeScheme has now "crisped" its images...

**Comment by schanzer** [comment]
Ah, I see - and you know what, Joe pointed this out to me during the merge and I fixed it...only to unfix it in a later commit. At the moment, WeScheme does NOT crisp its images. I have a handle on what's wrong now, and will need some time to fix it.

**Comment by schanzer** [comment]
Okay, I think I've got some insight now. The half-pixel adjustment is ONLY needed when we're drawing outline shapes, since `ctx.stroke()` draws **on** the pixel boundaries. Meanwhile, `ctx.fill()` draws **inside** them.

Pushed https://github.com/bootstrapworld/wescheme2012/commit/90c116b3dbff7522eb0f91b1ee231f0a518aefa6 to WeScheme, which seems to address all of these issues.

**Comment by blerner** [comment]
That looks encouraging: mimicking those changes into image-lib.js does seem to fix the weirdness above.  I haven't checked whether it un-crisps the image cases that Shriram was worried about before, but it hopefully shouldn't affect that...

Digging into the W3C documentation on `fill` and `stroke`, yes, it does appear that that's the case, and graphically it makes sense: a path is like a geometric line - it has no thickness.  So to "stroke" a path, you have to actually create a new path that surrounds the original one, and then fill the derived path.  (Adobe has known about this forever; PDFs have the option, when stroking a path, to specify whether your stroke is "inside", "on", or "outside" the path.  W3C hasn't figured this out, so they specify exactly that your stroke is centered "on" the path.)  Hence the half-pixel bugs we're seeing.  Meanwhile the fill rule counts from the top-left corner of a pixel: it starts filling any pixels at or after the coordinates it's given, and stops filling again at or after the next coordinates.  So it renders a semi-open interval `[start, end)`, which makes it easy to express canvas operations in terms of widths ("a 100px-wide rectangle starting at pixel 15"), and makes it easy to concatenate images side-by-side.  Hence your "solid" images, when on exact-pixel boundaries, were both crisp and the correct width.

It's fortunate that we don't allow users to specify stroke widths, or we'd have a helluva time trying to make them all crisp (it's practically impossible for anything but perfect rectangles, because if a stroke is centered on a half-pixel, then an odd-width stroke will be crisp and an even-width stroke will be blurry, and vice versa if we're on an exact-pixel boundary).

I'm not in a clean checkout state right now, so go ahead and port these changes to Pyret on horizon branch.

**Comment by schanzer** [comment]
Done: https://github.com/brownplt/code.pyret.org/commit/d7f71df857e59c9380abf68232feb6308f43679b

**Comment by schanzer** [comment]
I believe this is fixed, but I'm labeling it as paper-cut as per @blerner 's instructions.

**Comment by schanzer** [comment]
@blerner , this appears to be fixed on production CPO. Safe to close?

**Comment by blerner** [comment]
Yup, LGTM
