### ISSUE TITLE
Parameter to control the radius of a pie chart

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#108]
Right now, pie charts decide on their size when created; it would be useful to control their size with a radius parameter.

**Comment by blerner** [comment]
In the group discussion last week, they also requested being able to resize the chart in the popup window by resizing the popup window.

**Comment by jpolitz** [comment]
Do you have a sense of "would be nice" vs. "can't do my course without" for the various requests?

**Comment by blerner** [comment]
This one was a medium-strong request: these teachers use pie charts to indicate the energy budget of a system, with the relative wedge sizes indicating e.g. the proportions of kinetic to potential to chemical to heat energy, say.  But then they use the radius to indicate the actual total amount of energy, with "bigger radii == more energy".  So they really wanted some visceral action to "add energy to the system".

**Comment by sorawee** [comment]
OK. In Google Charts, there's nothing like this. The closest thing I can get is the exploded pie chart which looks like this.

![screenshot from 2017-07-23 16-15-30](https://user-images.githubusercontent.com/9099577/28502525-2ccd2502-6fc2-11e7-82ec-2fd9150a763d.png)

Is this acceptable?

**Comment by blerner** [comment]
I don't think they wanted individual radii per slice; I thought they wanted an overall radius set for the whole thing.  But I'm really not sure anymore.

**Comment by sorawee** [comment]
Since resizing will make the chart bigger/smaller, is it enough to say please resize it?
