### ISSUE TITLE
Bad line-plot

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#111]
```
include plot

display-line('test', table: x, y
    row: 100, 100
    row: 100, 101
  end)
```

results in 

```
An unexpected error occurred: TypeError: Cannot read property 'length' of undefined
```

**Comment by blerner** [comment]
Well, this is better(?) now: the same program results in 
```
Evaluating a expression in <builtin builtin://plot> errored.

It was expected to produce a "Pyret Value", but it produced a non-"Pyret Value" value:
    nothing
(Hide program execution trace...)

Evaluation in progress when the error occurred (most recent first):
builtin://plot:508:2-508:17
builtin://plot:397:2-399:21
definitions://:2:0-5:6
    display-line('test', table: x, y
```
Still seems wrong, though -- `nothing` is indeed a Pyret value, so something else is haywire here  @sorawee is this code supposed to work? And if it *isn't*, then what should the intended error message be?  And why is it getting `nothing` instead?

**Comment by sorawee** [comment]
@blerner I need to take a look a little bit more, but it seems that the value returned from `plot-lib.js` is `undefined`. For example, try:

```
import plot-lib as P

P.histogram({x-axis: "", y-axis: "", xscale: 0, yscale: 0, interact: false, title: ""}, table: value :: Number
    row: 1
    row: 2
  end._rows-raw-array, 4)
```

should produce `"<Unknown value: details logged to console>"`

Now, try:

```
import plot-lib as P

_ :: Nothing = P.histogram({x-axis: "", y-axis: "", xscale: 0, yscale: 0, interact: false, title: ""}, table: value :: Number
    row: 1
    row: 2
  end._rows-raw-array, 4)
```

would print the above error instead.

This code is supposed to work. I don't know why it fails. It works fine on master branch (whose code is pretty much identical to horizon). I will investigate when I have time.

**Comment by sorawee** [comment]
@blerner in `ffi.js`:

```
function throwTypeMismatch(val, typeName) {
      // NOTE(joe): can't use checkPyretVal here, because it will re-enter
      // this function and blow up... so bottom out at "nothing"
      if(!runtime.isPyretVal(val)) {
        val = runtime.namespace.get("nothing");
      }
      runtime.checkString(typeName);
      raise(err("generic-type-mismatch")(val, typeName));
}
```

**Comment by schanzer** [comment]
This no longer produces an error. Closeable?

**Comment by sorawee** [comment]
This is not about plot library anymore, but is about how undefined is recognised as nothing. I'll close this and open a new issue.

**Comment by blerner** [comment]
No, this isn't that either.  It's a stack-safety issue somehow: the initial code above currently runs in both Fx and Chrome on my linux laptop.  The middle code above fails with a lousy error message,
```
Evaluating a field lookup expression in <builtin runtime> errored.
does not have a field named extend-x
Please report this as a bug.
```
(Notice, I don't know what doesn't have a field named extend-x, since the message doesn't say.)  @sorawee could you look into what in the plot library might be failing there, or whether the code example is simply out of date?
