### ISSUE TITLE
Weirdness with `provide *`, `examples` and the indenter

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#113]
The following program does not indent properly -- nothing indents:

```
provide *
examples:
5 is 6
end
fun foo(x):
x * 2
end
```

If I remove the `provide *` then everything indents correctly:

```
# provide *
examples:
  5 is 6
end
fun foo(x):
  x * 2
end
```

If I rename `examples` to `check`, everything indents correctly:

```
provide *
check:
  5 is 6
end
fun foo(x):
  x * 2
end
```

And if I reorder the two blocks, then the function indents but the examples doesn't:

```
# provide *
fun foo(x):
  x * 2
end
examples:
5 is 6
end
```

**Comment by blerner** [comment]
This appears fixed on horizon now; @belph confirm that you'd handled this?

**Comment by belph** [comment]
@blerner Correct, it should be fixed
