### ISSUE TITLE
Rational toggle for float computation looks odd

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#12]
Playing with rational toggling, just got the following output:

![image](https://cloud.githubusercontent.com/assets/119891/3015146/b9c4bd22-df5f-11e3-83dc-a86316de8731.png)

I don't really understand what's going wrong there.

**Comment by blerner** [comment]
This seems like it's been fixed somewhere along the line...

**Comment by blerner** [comment]
Actually it's fixed on CPO/master, too.  Closing.
