### ISSUE TITLE
imported code leaks test cases

### ISSUE THREAD

**Issue by awstlaur** [brownplt/code.pyret.org#121]
Reproduce: go to [thing.arr] (https://code.pyret.org/editor#share=0Bz8lcSxx1xz6M21LTmdUZEdCQmc&v=80ba55b), hit Run. Notice that the tests from the imported `support.arr` are also run.

`support.arr`:
```
provide *
provide-types *

fun supportHelper(x):
  x
where:
  supportHelper(3) is 3
  supportHelper("hello") is "hello"
end
```
`thing.arr`:
```
import shared-gdrive("support.arr", "0Bz8lcSxx1xz6RmFFUzBFMDR3dG8") as S

fun someFunction(x):
  S.supportHelper(x)
where:
  someFunction(10) is 10
end
```

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/6d2ea67155123624317536da0cae839d85c55c08 and cb8e5bdf99097cce5115b8346e6621cb01434e42, af47f6364c68d1155c7fc48a4b3d9da3837d585b

**Comment by jpolitz** [comment]
Oops, some issue remains.  Weird.  I'll figure out why this wasn't a complete fix.

**Comment by jpolitz** [comment]
OK, _now_ this looks fixed to me.  I pushed CPO before I pushed pyret-lang, so the change was only half-deployed.  Can you confirm, @awstlaur?

**Comment by awstlaur** [comment]
Can confirm this is fixed on code.pyret.org.
