### ISSUE TITLE
`logger` not defined on index page

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#126]
The index page has logger code included that seems to be broken – `define` is not defined and `logger` is not defined.

This seems like logging updates broke this.

<img width="1280" alt="screen shot 2016-09-23 at 9 49 41 am" src="https://cloud.githubusercontent.com/assets/119891/18787982/1f0f6710-8173-11e6-82ef-d0c86bf73ef7.png">

**Comment by jpolitz** [comment]
This stops `Log in` from changing to `My Programs`, which confused some students.

**Comment by jswrenn** [comment]
To fix this, I believe we just need to add a script tag importing `log.js` on this page.

**Comment by jpolitz** [comment]
If I add that, I get the following, which seems like the logger depends on CodeMirror and requirejs?

I don't really understand the use of `define` in `authenticate-storage.js`.  Isn't that just using requirejs to create a glorified global variable?

<img width="1271" alt="screen shot 2016-09-23 at 10 45 46 am" src="https://cloud.githubusercontent.com/assets/119891/18789981/0ad264e8-817b-11e6-8a04-86ce8e7fd63e.png">

**Comment by jswrenn** [comment]
Curses! Yeah, at the end of `log.js`, there's a CodeMirror event hook gets registered. Besides a message printed to the console, I think that should affect absolutely nothing (it would cause executing `log.js` to fail, but that event hook is registered _after_ `logger` is defined).

The use of `define` in `authenticate-storage.js` isn't some logging added, is it?

**Comment by jpolitz** [comment]
You're right about the authenticate-storage stuff, that's from a prior change.  I'll look into that.

We should at least check if CM is defined in the logger, to avoid cluttering up error message space.

**Comment by schanzer** [comment]
I'm no seeing these errors in the console these days... @jpolitz is this still an issue?
