### ISSUE TITLE
triangle-sss doesn't take roughnum

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#127]
<img width="441" alt="screen shot 2016-09-25 at 8 52 17 pm" src="https://cloud.githubusercontent.com/assets/9099577/18819634/5ee6b1a4-8362-11e6-9076-3a1d53d9e9cb.png">

**Comment by sorawee** [comment]
In general, `image.js` needs to be rewritten to take roughnum and rational into account. All math functions / operators need to be switched to jsnum call.

**Comment by schanzer** [comment]
@sorawee this example now runs correctly on CPO. OK to close?

**Comment by sorawee** [comment]
Yup
