### ISSUE TITLE
REPL caret not centered

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#128]
Making a note that the REPL caret isn't vertically centered with the text entry:

<img width="645" alt="screen shot 2016-10-05 at 10 08 31 am 1" src="https://cloud.githubusercontent.com/assets/119891/19116514/cbe8da2e-8ae3-11e6-85ea-ce8e33dca3de.png">

I honestly don't know if this is new or not, but now that @schanzer has mentioned it, it's bugging my eyes.

**Comment by jswrenn** [comment]
Ack, I think I did this in `9782ac5ba35fc20b0d087e86a02a003077c11df9`. I thought I pushed my fix, but apparently not.
