### ISSUE TITLE
Error rendering bug with invalid type alias

### ISSUE THREAD

**Issue by awstlaur** [brownplt/code.pyret.org#129]
Code:

```
import string-dict as SD

type NumDict = SD<Number>

fun someFunction(d :: NumDict) -> NumDict:
  d
end

someFunction([SD.string-dict:])
```

Click Run, get message:

```
Internal errors prevented this error message from being shown. Please report this as a bug.
```

(In case you don't spot it, the second line should be `type NumDict = SD.StringDict<Number>`)

**Comment by blerner** [comment]
This seems to be because Pyret's checkAnnotation doesn't actually first check whether the annotation is in fact an annotation at all.  Closing this and moving to https://github.com/brownplt/pyret-lang/issues/1039
