### ISSUE TITLE
SSL Certificate error on code.pyret.org

### ISSUE THREAD

**Issue by pcardune** [brownplt/code.pyret.org#131]
See screenshot of the certificate chain when going to https://code.pyret.org in chrome. When using safari, it works fine and has a different chain.

<img width="488" alt="screen shot 2016-10-18 at 10 09 46 am" src="https://cloud.githubusercontent.com/assets/124827/19488302/18201c4a-951b-11e6-9f9d-e4ae3908bc09.png">

**Comment by blerner** [comment]
This seems to no longer be an issue...
