### ISSUE TITLE
Spyret on Pyret IDE

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#141]
- [ ] Rendering components for Scheme-shaped values
- [ ] Open images, import code, should be Scheme formatted
- [ ] Blocks should be an option for combining with editor modes

**Comment by schanzer** [comment]
This is essentially done in Patch (blocks coming shortly)

**Comment by schanzer** [comment]
R.IP., Spyret

@jpolitz suggest we close?

**Comment by schanzer** [comment]
Closing.
