### ISSUE TITLE
Can't see the cursor in the REPL

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#143]
![snippet](https://cloud.githubusercontent.com/assets/918464/19603889/d5ac5c94-9780-11e6-9e2e-2a159b4f37eb.png)

This is on Firefox on Windows.  @jswrenn does this have to do with any of the styling changes (I think I recall) you'd made recently?

**Comment by blerner** [comment]
If I type any one character, it's not visible.  Typing a second makes them both appear...

**Comment by jswrenn** [comment]
It almost certainly does. Will push a fix ASAP.

**Comment by schanzer** [comment]
I don't have windows, so I can't replicate. Is this still an issue?

**Comment by schanzer** [comment]
@blerner is this still an issue? I can't reproduce it on Chrome/OSX
