### ISSUE TITLE
odd error when `include`ing code that has `provide {...}` and `where`

### ISSUE THREAD

**Issue by awstlaur** [brownplt/code.pyret.org#144]
`to-be-included.arr`[1]:

```
provide {
    some-fun: some-fun
} end


fun some-fun():
  4
where:
  some-fun() is 4
end
```

`include-the-other-file.arr`[2]:

```
include my-gdrive("to-be-included.arr")
```

When running the latter file, we see:

```
Evaluating a field lookup expression in <builtin runtime> errored.
does not have a field named result-after-checks1
Please report this as a bug.
(Hide program execution trace...)
Evaluation in progress when the error occurred (most recent first):
```

[1] https://code.pyret.org/editor#share=0Bz8lcSxx1xz6SFg5WWQ1M0dkU0k&v=08d40a4
[2] https://code.pyret.org/editor#share=0Bz8lcSxx1xz6bXlJdy1GZU45NVk&v=08d40a4

**Comment by sorawee** [comment]
It's the same issue in https://github.com/brownplt/pyret-lang/issues/740

**Comment by blerner** [comment]
This now works
