### ISSUE TITLE
bad error surrounding using types from include code

### ISSUE THREAD

**Issue by awstlaur** [brownplt/code.pyret.org#145]
`data-to-include.arr`[1] has `provide *`, but no `provide-types` statement, and defines `data Thing`. `include-data-here.arr`[2] `include`s it and uses `Thing` as a type annotation. Badness ensues. See screenshot [3], which includes both check results and repl result, the latter of which says "Please report this as a bug."

[1] https://code.pyret.org/editor#share=0Bz8lcSxx1xz6OVhId0lfMWJzcUk&v=08d40a4

```
provide *

data Thing:
    thing(a :: Number)
end
```

[2] https://code.pyret.org/editor#share=0Bz8lcSxx1xz6eGR1R0M5ZDhKMkk&v=08d40a4

```
include shared-gdrive("data-to-include.arr", "0Bz8lcSxx1xz6OVhId0lfMWJzcUk")

fun is-thing-valid(t :: Thing) -> Boolean:
  true
end

check "is-thing-valid":
  is-thing-valid(thing(0)) is true
end
```

[3]
![issue-with-include-oct-27](https://cloud.githubusercontent.com/assets/8000562/19789063/9fd401b8-9c7a-11e6-893c-92c3131e9048.png)

**Comment by blerner** [comment]
This error is now fixed; @jpolitz ok to close?
