### ISSUE TITLE
Show logged-in account in UI somewhere

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#147]
Lots of folks have multiple Google accounts.  The UI should reflect which account they are logged in as (e.g. "Welcome, joe.politz@gmail.com!" somewhere in a toolbar or under 'More')

**Comment by blerner** [comment]
This is addressed now, right?  The new Bonnie menu has the account name right at the top.

**Comment by schanzer** [comment]
Definitely fixed. Closing.
