### ISSUE TITLE
Student unable to open gdrive files

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/code.pyret.org#149]
A student in cs173 is unable to open their gdrive files in CPO. They write:

> When I try to open a file from my google drive, it says:
> "Sorry, we were unable to authorize this app for all of the files you attempted to open. Please try again."
> I've tried signing out and signing in, duplicating the file, clearing cookies, opening it in incognito mode, using another browser... none of these solutions worked.
> I created a new file in pyret (clicked "Start Coding"), saved it, then tried to open this new file.  I still get the same error.

**Comment by jpolitz** [comment]
Did they log out of Pyret? The most likely cause is a Pyret cookie that's referring to a different Google account.

**Comment by justinpombrio** [comment]
Jared, here's the github issue. Joe asks:

Did they log out of Pyret? The most likely cause is a Pyret cookie that's
referring to a different Google account.

**Comment by shriram** [comment]
The student says, "I've tried signing out and signing in, duplicating the file, clearing cookies, opening it in incognito mode, using another browser... none of these solutions worked."

He added, "I created a new file in pyret (clicked "Start Coding"), saved it, then tried to open this new file.  I still get the same error."

**Comment by jpolitz** [comment]
Another thing to check is if Pyret is listed as a connected app at https://security.google.com/settings/security/permissions?pli=1

**Comment by jtsiskin** [comment]
It is listed as a connected app.
I never logged out of pyret; after it stopped working I tried logging out and logging back in both out of pyret and google but that did not fix the issues.
The same error message that displays in pyret displays on google drive.
It can create and save files to my google drive, but then it is unable to open them.
It is unable to read files using "import _ from _" in the google drive either.
![image](https://cloud.githubusercontent.com/assets/11904459/20247435/38f95164-a99a-11e6-8971-f4ecfe631ad7.png)
![image](https://cloud.githubusercontent.com/assets/11904459/20247414/a6a3ff12-a999-11e6-86f2-bd4727998c54.png)
![image](https://cloud.githubusercontent.com/assets/11904459/20247425/fab8a9cc-a999-11e6-8eb8-13667ef32c94.png)
<img width="1266" alt="screen shot 2016-11-13 at 12 05 58 pm" src="https://cloud.githubusercontent.com/assets/11904459/20247412/95cc6b84-a999-11e6-9dc5-4ee1b7e93dc9.png">

**Comment by jpolitz** [comment]
Thanks, this was really helpful.  It looks like it may be an issue on Google's end:

https://productforums.google.com/forum/#!topic/apps/weFHNRWu5iw

I'll keep looking into it, but it may work to _remove_ access to code.pyret.org on the Google permissions screen, and then re-log-in and re-authorize CPO.

Sorry for the annoyance; I've tried for a while to reproduce this and can't find a combination of login/account settings that give me the same error, so I can't say exactly what situation is causing this yet.

**Comment by jpolitz** [comment]
I see you already tried my suggestion, and it didn't work, sorry.

Do you have another Google account you would be willing to try?

**Comment by jtsiskin** [comment]
Yes; to complete my assignment I logged in/authorized with a different google account and copy/pasted my code.  It has been working without issue

**Comment by schanzer** [comment]
Ok to close?

**Comment by schanzer** [comment]
@blerner this issue is ancient, and overall GDrive opening seems to have been stable for quite some time. OK to close?

**Comment by blerner** [comment]
Yeah; the recent GDrive weirdnesses (with files disappearing from some physics sims) seems to be unrelated, so we'll reopen this if it becomes reproducible...
