### ISSUE TITLE
Code unfolds after clicking Run.

### ISSUE THREAD

**Issue by awstlaur** [brownplt/code.pyret.org#151]
Code folding is great, but not when the editor undoes it for you. :(

To reproduce:
- Write some indented code
- Use the little gutter arrow to fold it
- Click Run

**Comment by blerner** [comment]
Not 100% sure why we do that, but I'm willing to bet it has something to do with the error-highlighting we want to do for check blocks and runtime errors...  Pinging @jswrenn

**Comment by jswrenn** [comment]
Yep! The code folding implementation involves adding gutter markers and text markers, but doesn't exclude these markers from the [clear-highlights routine](https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/cpo-main.js#L360-L369). I'll have to look into the code folding implementation, but it should be fairly simple to not remove gutter markers or text markers with whatever CSS classes are added by the folder.

I can take a look into it later this week.

**Comment by schanzer** [comment]
@jswrenn this is still an issue. Any chance you can still take a look?

**Comment by jswrenn** [comment]
Thanks for poking me again on this. It'll be *slightly* more complicated to fix than I thought, but it's at the top of my TODO list for tomorrow.

**Comment by jswrenn** [comment]
Fixed!
