### ISSUE TITLE
1 and l sometimes look the same

### ISSUE THREAD

**Issue by jswrenn** [brownplt/code.pyret.org#152]
A student (using chrome on a mac) sent me this image:
![1lhomoglyphs](https://cloud.githubusercontent.com/assets/3820879/20496143/f14eaf90-aff1-11e6-8f60-34752a08ef12.png)

For me (using chrome on linux), they look sufficiently different:
![1l](https://cloud.githubusercontent.com/assets/3820879/20496190/2535dea0-aff2-11e6-924f-7738f0d6f312.png)

We may want to consider suggesting a particular monospace font in the CSS rather than using the system default.

**Comment by schanzer** [comment]
Here's our CSS declaration: `"Droid Sans Mono", Monaco, monospace`. Works quite well.

**Comment by belph** [comment]
I think [Hack][hack] is the default on the pyret.org website (I may be misremembering, though). Regardless, I'll plug for it, since it's my monospace font of choice for Latin scripts. 

[hack]: https://github.com/chrissimpkins/Hack

**Comment by schanzer** [comment]
@blerner CPO is using a different font now from whatever it used in 2016, and these characters are more easily-differentiable. Suggest we close.

**Comment by blerner** [comment]
Up to you, ok.
