### ISSUE TITLE
Smart quotes in interactions

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#154]
Smart quotes nicely replace with straight quotes in the definitions window on paste, but don't in the interactions pane – they should work in both places.

**Comment by SethPoulsen** [comment]
It looks like in [cpo-main.js](https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/cpo-main.js), line 442 is what takes care of this for the definitions window:
`      editor.cm.on('beforeChange', curlyQuotes);
`
It should be as simple as attaching the same handler to the cm object representing the REPL, but I couldn't find where that is initialized.

**Comment by SethPoulsen** [comment]
Update: adding the line 
```Javascript
editor.cm.on('beforeChange', curlyQuotes);      
CPO.documents.get("definitions://").cm.on('beforeChange', curlyQuotes);
```
Makes it so the curly quotes adjust when pasted in the REPL (the undo doesn't work, but that's the next step). I'm sure there is a better way to do this that involves attaching the handler when the REPL is created, rather than later.

**Comment by blerner** [comment]
I think you're looking for `repl-ui.js`, line 706, which is where the definitions REPL is created.  But that'll take you out of the scope where `curlyQuotes` is defined, so that might be a bit tricky.  I'm not sure why undo isn't working for you...

**Comment by SethPoulsen** [comment]
@blerner Thanks. 

I pulled the curlyQuotes function out to a separate file so that it can be referenced from where the editor is created and from where the repl is created. It works nicely.

**Comment by SethPoulsen** [comment]
Any reason this one is still open?
