### ISSUE TITLE
Wide tables in the REPL block the vertical divider

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#156]
1) Import/Make a table with lots of columns, then evaluate it so it displays in the REPL
2) You can't see all the columns, so you scroll...
3) The left-most columns show above the divider, so I can't resize the REPL anymore!

**Comment by schanzer** [comment]
Whoa - the REPL text-entry boxes _also_ cover the divider in this situation. Looks like we need to set overflow: scroll on table boxes.

**Comment by schanzer** [comment]
Adding this line to editor.css out to do it:

`#output > * {overflow-x:scroll;}`

**Comment by jpolitz** [comment]
I played with this a bit today; I think that `#output { overflow-x: scroll }` is a little better.

The effect that has is to make the whole region above the prompt left/right scrollable if anything is too wide.

Making everything scrollable individually causes lots of scrollbars to appear if you print things out near the width of the REPL window, which gets crazy busy visually.

**Comment by schanzer** [comment]
That solution works for me! I wasn't sure if there were other rules making assumptions about the entire output being unscrolled.

**Comment by schanzer** [comment]
I can't replicate this issue.
