### ISSUE TITLE
Show logged-in username in dashboard

### ISSUE THREAD

**Issue by kevinschaich** [brownplt/code.pyret.org#161]
After some research I think this requires the Google Plus scope added in addition to just Google Drive access. Will need to load additional API libraries etc.

**Comment by kevinschaich** [comment]
After some reserach I think this requires the Google Plus scope added in addition to just Google Drive access. Will need to load additional API libraries etc.

**Comment by schanzer** [comment]
This is now visible in the dashboard. Closing.
