### ISSUE TITLE
Files should open in a new tab

### ISSUE THREAD

**Issue by kevinschaich** [brownplt/code.pyret.org#164]
(And use target to prevent repeated tabs when opening the file again)

This was the behavior we originally had but opted for same-tab instead. Do you think if we add a button in the IDE to "return to dashboard," it would be more intuitive to open in a new tab or same tab?

I think it just might be confusing if they have the dashboard open in another tab and then "return to dashboard" doesn't work when they click it.

**Comment by schanzer** [comment]
"return to dashboard" should switch to the dashboard tab if it's already open, and open a new tab if it's not.

It's an extremely common use case to have the list of programs open in one tab, and a program you are editing in another.

**Comment by kevinschaich** [comment]
Is this technically feasible? I'm not sure that modern browsers have a notion of "switch to this tab if it's open" via Javascript.

This could be further complicated if people have multiple browser windows open.

**Comment by michaelmauer** [comment]
Also, I think that it might make sense to just open in a new tab and not bother taking control of how the tab changes if we close the IDE one. You don't always want to go back to the dashboard after closing the IDE, I think.

**Comment by awstlaur** [comment]
Another option could be to implement custom tabs on the web app, akin to how a google sheets document has tabs for different sheets in the same document. Except the tabs would have separate documents. (I think @jswrenn mentioned this idea in person to me at one point).

**Comment by shriram** [comment]
That seems like a huge implementation problem (cheap to ask, hard to build
*well*, taking dozens of UI issues into account).

**Comment by schanzer** [comment]
This is not a js issue - HTML itself allows you to load pages in named windows. Easy to implement. 

(WeScheme has done this for years)

**Comment by kevinschaich** [comment]
Pull request later today will resolve this, but I encountered some errors along the way with Chrome's popup blocker thinking that the "open IDE in a new tab" was spam.
