### ISSUE TITLE
"Save image" button in plot window navigates page in Safari

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#166]
In Safari, the "Save" icon in the top bar of plot windows navigates the page to a data URL.

It should either force a download or open the image in new tab.

It also isn't a link, so I can't right-click it and "Open in new tab".

**Comment by sorawee** [comment]
@jpolitz does it work fine on Chrome on your computer?

**Comment by sorawee** [comment]
@jpolitz can you confirm that this is still happening? It works fine for me... The tricky part is that I don't have a Mac anymore, so debugging is going to be difficult...

**Comment by schanzer** [comment]
@jpolitz safari now behaves correctly. I propose we close.

**Comment by schanzer** [comment]
Closing.
