### ISSUE TITLE
Low image quality when saving images from plot library

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#174]

**Comment by sorawee** [comment]
Apparently this is a normal `getImageURI` issue. Close as won't fix.

**Comment by blerner** [comment]
Can you say more about the problem and the reason it's a "normal" issue?  Why use getImageURI, as opposed to toDataURL or some other standard canvas API?

**Comment by sorawee** [comment]
I don't know about `toDataURL`. I just happen to use `getImageURI` since the first version of the library. Coincidentally, this is `getImageURI` is how Google suggests us to export to PNG (https://developers.google.com/chart/interactive/docs/printing). I'll see what `toDataURL` is, and if it helps with quality, I will change.
