### ISSUE TITLE
empty-scene should take (background) color argument?

### ISSUE THREAD

**Issue by ds26gte** [brownplt/code.pyret.org#181]
Pyret's `empty-scene` currently takes two arguments: width and height. WeScheme's `empty-scene` takes a third, optional, argument for (background) color. 

Should we add a third (non-optional) argument to Pyret's `empty-scene`, or have a separate procedure that takes the third argument?

**Comment by shriram** [comment]
I prefer a separate one. Let's keep the default operators simple.

**Comment by schanzer** [comment]
Especially if scenes are ultimately going away (see new image API)

**Comment by ds26gte** [comment]
What's a good name for this procedure? `empty-color-scene`, `empty-colored-scene`, `empty-scene-color[ed]`, `empty-colored-background`, ...?

**Comment by schanzer** [comment]
`empty-color-scene` works for me. No BS courses use it, and it's almost certain to be deprecated quickly.

**Comment by blerner** [comment]
Available in horizon.
