### ISSUE TITLE
Call cm.refresh() when divider bar is dragged

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#186]
1) Open a file (ideally with long-ish lines) on CPO, and select something
2) Resize the divider so that the line-wrapping changes

EXPECTED: selection moves along with the lines
ACTUAL: selection stays where it is

**Comment by blerner** [comment]
Fair warning: in the past, we've tried various things that we thought "oh, that'd be fixed by calling cm.refresh()", and then they weren't.  So the subject of this bug might be a wee bit optimistic ;-)

**Comment by schanzer** [comment]
Whatever's happened since then, I can no longer reproduce this issue. Closing.
