### ISSUE TITLE
Image thumbnails on projector today

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#194]
We were presenting (in Chrome) today, this file: 

https://code.pyret.org/editor#share=0B9rKDmABYlJVaUw0VjdiOE5DVzQ

We were at a projector, not zoomed in too far, and a few times the images wouldn't show up the first time we entered them in the REPL

**Comment by schanzer** [comment]
Try as I might, I have not been able to reproduce this. And if this were still happening, I think we'd be hearing about it a lot more.

Suggest we close?

**Comment by schanzer** [comment]
@jpolitz ok to close?

**Comment by schanzer** [comment]
This appears to be fixed - no one has reported this over in Bootstrap-land for many years, and Safari itself has certainly improved a lot since 2020.
