### ISSUE TITLE
"Save as.." should be "Make a copy"

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#195]
Anyone who can save at all is already a GDocs user, and "Save as" has no meaning to them. Let's stick with the GDocs convention instead.

**Comment by jpolitz** [comment]
I disagree that following GDocs conventions is at all helpful, or that we
can assume teachers are “GDocs users”.

The old interface did the same thing as GDocs on rename, and it really
annoyed some teachers.

On Wed, Jul 19, 2017 at 8:51 AM, Emmanuel Schanzer <notifications@github.com

**Comment by schanzer** [comment]
Interesting. I was always under the impression that people would be GDocs users, since they need a google ID to log in and all files are saved to GDrive. But even if that's not true, "Make a copy" is a far more common-sense phrase than "Save As".

**Comment by blerner** [comment]
Split the difference: "Save a copy..."

**Comment by shriram** [comment]
"Save a copy" is better than either of the previous options!

**Comment by blerner** [comment]
This is fixed; Shriram's new complaint about the initial save of a shared file is a separate issue, to be fixed separately.

**Comment by schanzer** [comment]
Personally, I think "save a copy" gets us most of the way there for #205, and does a great job here. "Save a copy to my Drive" would be even clearer, but it's so too long.
