### ISSUE TITLE
"Create chart" button on table output

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#199]
In the upper-right of tables, there's a clipboard icon to copy the data.

Why not also have a _chart_ icon, which opens a dialog to create a plot, similar to how it works in Google Charts (heck, it could create a sheet, open the sheet, and maybe even pop up the Chart creator with a little script).

This avoids needing a `plot` library for very simple examples (the `plot` library is obviously still useful for programmatic creation of plots).

**Comment by sorawee** [comment]
How do we specify the type of chart?

**Comment by schanzer** [comment]
This feels like something we don't really want. Implementing this feature will:

- require a lot of UI thinking
- increase the surface area of CPO
- potentially add pedagogical dependencies (the UI should work a little like the API, but what if the API changes?)
- incentivize users to ignore the programmatic API altogether

Personally, I'd be really bummed if this was implemented.

**Comment by jpolitz** [comment]
I was thinking about this for the outputs of tracing reactors, but I'm going to close as not worth it.
