### ISSUE TITLE
Problems with guessing error locations

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#20]
Arity mismatches and a few other errors use a heuristic of "the top user-defined stack frame" to guess the location to report.  If the stack doesn't have any frames (for whatever reason), or if the stack consists only of built-in frames, `undefined`s can result and break other parts of the rendering.  This needs a more principled solution for what to show.

**Comment by blerner** [comment]
@jpolitz , @jswrenn : how much of this bug is still relevant?

**Comment by schanzer** [comment]
@blerner is this still an issue?

**Comment by shriram** [comment]
If this is still an issue it'll crop up as a fresh one. Closing.
