### ISSUE TITLE
CPO highlighting of srclocs for interactions is wrong

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#202]
"This code is not in this editor"

**Comment by shriram** [comment]
But see the more elaborate comment at #1109.

**Comment by sorawee** [comment]
Even when the code is in the definition window editor, "this code is not in this editor" still appears. See #187.

**Comment by schanzer** [comment]
@blerner is this still an issue?

**Comment by schanzer** [comment]
@blerner OK to close?

**Comment by schanzer** [comment]
@blerner OK to close?

**Comment by blerner** [comment]
Dunno, probably.
