### ISSUE TITLE
CPO issues in Edge

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#204]
- [ ] Large-enough fonts (28+px) screw up clicking to get to a given line
- [ ] Clicking on the File menu, then clicking Save as, doesn't dismiss the menu
- [ ] Publish doesn't work (gets a 403 XHR error "The server understood the request, but is refusing to fulfill it." on the url https://code.pyret.org/create-shared-program)

**Comment by schanzer** [comment]
@blerner given the very short lifetime that non-Chromium Edge had, do we still care about this?

**Comment by blerner** [comment]
Probably not
