### ISSUE TITLE
different symbol for interactions prompt?

### ISSUE THREAD

**Issue by shriram** [brownplt/code.pyret.org#208]
![image](https://user-images.githubusercontent.com/75030/28840957-a9a31f22-76c6-11e7-9b46-9d920203ca55.png)
looks rather weird. Since code is text, how about using a non-text glyph for the prompt? (People even have trouble vocalizing it: they call it "the greater than sign", etc.)

**Comment by sorawee** [comment]
`>>>` :)

**Comment by schanzer** [comment]
Perhaps the `>` prompt could be in a different font-weight and color (I'm thinking gray, so it stands out less than the code that's next to it)

**Comment by blerner** [comment]
Hah! Same as #269, now ;-) Closing as dupe, since that one has more information now.
