### ISSUE TITLE
Wrong alpha range

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#211]
In `image-lib.js`:

```
var colorAlpha = function(c) { return clamp(jsnums.toFixnum(unwrap(gf(c, "alpha"))), 0, 1); }
```

But we recently changed alpha's domain to 0-255.

**Comment by blerner** [comment]
No, we switched to 0-1, for better arithmetic.

**Comment by schanzer** [comment]
In that case, isn't think issue moot? OK to close?

**Comment by blerner** [comment]
Yes
