### ISSUE TITLE
New primitive image type: pie-wedge

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#214]
I'd like to be able to draw the wedges of a pie-chart, or to draw PacMan.  To do this, I think I want the following signature:

```
pie-wedge :: (angle-in-degrees :: Number%(between(0, 360)), 
              mode :: String, 
              wedge-color :: Color, background-color :: Color) -> Image
```

This would draw a wedge of the given angle in the given color, from the x-axis counterclockwise, overlaid on a circle of the given background color.  If mode is "solid" both parts are filled in; if mode is "outline" then the wedge and circle are outlined.  The reason for requiring a background circle is so that if you draw `pie-wedge(60, "solid", "red", "transparent")` and another `rotate(60, pie-wedge(60, "solid", "blue", "transparent"))`, you can `overlay` them on each other and the circles will ensure alignment.

(I could also imagine a `raw-pie-wedge` function that skips the background circle and produces a tight bounding box, but I'm having a harder time finding uses for that.  Still, compositionality tells me we probably should have it, too, at least until we have pinholes again...at which point it will immediately become the more useful primitive.)

Uses: I can easily imagine building up a Trivial Pursuit kind of token, with six wedges rotated and overlaid on each other.  Similarly, we could have students write
```
fun draw-pie-chart-angles(a1, a2, a3, a4, a5, a6) -> Image:
  w1 = pie-wedge(a1, "solid", COLOR1, "transparent")
  w2 = rotate(a1, pie-wedge(a2, "solid", COLOR2, "transparent"))
  w3 = rotate(a1 + a2, pie-wedge(a3, "solid", COLOR3, "transparent"))
  ...
  overlay-images([list: w1, w2, w3, w4, w5, w6])
end

fun draw-pie-chart(val1, val2, val3, val4, val5, val6) -> Image
  sum = val1 + val2 + val3 + val4 + val5 + val6
  draw-pie-chart-angles(val1 / sum, val2 / sum, ...)
end
```
This would be great in the Qualitative Energy unit for physics folks, since they'll only have a small maximum number of wedges (and any unneeded ones could be given as 0 value), and makes the initial charting of energy both practice programming some more (coming right after practice with images) and less magical.

**Comment by schanzer** [comment]
@blerner I'm assuming this is probably intended for the new image library?

**Comment by blerner** [comment]
It can go in both -- the underlying primitive can be exposed to both libraries.

**Comment by blerner** [comment]
This is now implemented, pending one design decision about pinholes, which I'll ask in the other image-library issue...

**Comment by schanzer** [comment]
Since it’s implemented and pushed, any reason to keep it open?

**Comment by schanzer** [comment]
@blerner OK to close?

**Comment by schanzer** [comment]
Oh! Sorry, I thought there was a big horizon->master merge a while back.

**Comment by blerner** [comment]
This is now fixed on horizon with the new image library.
