### ISSUE TITLE
Share panel hides but does not die

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#22]
![screenshot from 2014-11-13 16 40 55](https://cloud.githubusercontent.com/assets/119891/5037225/f91a4304-6b53-11e4-98bf-5f88d056ae78.png)

They need to remove themselves from the DOM, or weird things start to happen.

**Comment by schanzer** [comment]
@jpolitz - Now that the sharing UI has been rewritten, is this still an issue?

**Comment by sorawee** [comment]
Yes, it's fixed. I missed this old interface....

@jpolitz should we remove the above image too? It contains a solution of the Java assignment.
