### ISSUE TITLE
Always position REPL at the caret

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#220]
Say I have:

```
fun f() block:
  print("hello")
  f()
end

f()
```

After clicking run, I hope to see the REPL position at the bottom. Currently, we only see the text going past the page, but the page itself is not repositioned as it should. Only when we click the stop button that the page moves to the bottom.

**Comment by schanzer** [comment]
@sorawee confirming this works correctly now (as soon as stop is pressed, the REPL scrolls to the caret)
