### ISSUE TITLE
Issue with image.color-list-to-bitmap

### ISSUE THREAD

**Issue by Solomonz** [brownplt/code.pyret.org#223]
When called on a list of image-struct.color, the color-list-to-bitmap function rounds the pixel values towards their extrema, resulting in incorrect color values.

For instance, a pixel in the original image with an RGB value of (150, 0, 0) will become (255, 0, 0) in the output.  A pixel (50, 50, 50) would have each value rounded down to 0 and become a solid black pixel. 

In addition, the CPO interface does not render any images that are output from this function; they all render as white rectangles. 

This issue may be related to clamping behavior included in the July 15th commit "Loosening the restriction on color components." In the code.pyret.org /src/web/js/trove/image-lib.js the functions clamp() and the color component function are a possible source. 

This was not a problem during the Fluid Images assignment last fall. 

**Minimum Working Example**
```
import image as image
import image-structs as image-structs
c  = image-structs.color(50, 200, 200, 1)
color-list = repeat(64, c)
img = image.color-list-to-bitmap(color-list, 8, 8)
output-color-list = image.image-to-color-list(img)

check "pixel values have been rounded to 0 or 255":
    output-color-list.first.red is 0
    output-color-list.first.green is 255
    output-color-list.first.blue is 255
end
```

**Comment by jpolitz** [comment]
Thanks and sorry about that, should be fixed by 2f3b1bb51c907811a7db16f6c7afbda6d9936f88, which will show up on the live site in ~30 minutes.
