### ISSUE TITLE
Text out of box

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#229]
![screenshot from 2017-09-02 04-59-07](https://user-images.githubusercontent.com/9099577/29994339-8b15a960-8f9b-11e7-84ec-9e860f5fa3ef.png)

**Comment by schanzer** [comment]
I can't reproduce this anymore (chrome/OSX). @sorawee , OK to close?

**Comment by sorawee** [comment]
Still happen to me everyday on Firefox

**Comment by blerner** [comment]
This is because Firefox and Chrome use different font rendering engines, and so their text metrics are different.  Two possible fixes: change editor.css, line 1288, to be 13px instead of 15px.  Or, change the superscript to say `(β)` instead of `(beta)`.

**Comment by schanzer** [comment]
This no longer happens in modern FF. The menu gets garbled in a _different_ way for super-narrow windows, but it does so consistently across browsers. Suggest we close.

**Comment by sorawee** [comment]
Cannot reproduce it now, too. Closing.
