### ISSUE TITLE
Support Apple shortcut keys

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#231]
Ctrl-S -> Cmd-S on MacOS

**Comment by YanyanR** [comment]
do you just mean instead of using Ctrl-S for saving, use Cmd-S?

**Comment by schanzer** [comment]
Yep. Keyboard shortcuts should behave as-expected, and consistently. Right now, on macs, CPO does neither.

**Comment by blerner** [comment]
Careful!  As your comment is phrased, CPO is just fine -- it's identically consistent across platforms, and performs admirably up to *our* expectations ;-)
