### ISSUE TITLE
Image library lacks types

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#234]
The image library has `tany` as the type for most of its functions.

I think, for typing, we should probably force `Color`, not `String`, as the type of the color position of shapes, which is an important mistake to not make when these are filled in.

**Comment by schanzer** [comment]
Now that Ben is working on the new (typed) Image library, this should basically be marked `wontfix`. @jpolitz , OK to close?

**Comment by schanzer** [comment]
With Ben’s new library landed, do we still need to keep this open?

**Comment by schanzer** [comment]
@jpolitz  OK to close?

**Comment by schanzer** [comment]
@blerner has it still not landed?

**Comment by jpolitz** [comment]
<img width="1901" alt="image" src="https://user-images.githubusercontent.com/119891/89937057-72411a00-dbc9-11ea-9380-41ef54392e5c.png">
