### ISSUE TITLE
Color swatch for color(0,0,0,0) doesn't use the standard "checkered" pattern

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#250]
Minor nit, but it caught me by enough surprise that it's worth fixing. If we add this, I'm not even sure we _need_ the word `transparent` to be shown after it.

(posting here since I assume the relevant code is actually in CPO?)

**Comment by blerner** [comment]
The reason we give the name whenever possible is so students know what the color is called. Eg `rgba(255,0,0,355)` says red, even though it's obvious that the constructor notation also suffices.

Using the checkerboard pattern is a good idea, I think I can easily add that to the svg image's fill.

**Comment by schanzer** [comment]
Ah, I didn’t realize you use the names whenever possible. Awesome. (Would be even cooler to have the name rendered *on top* of the swatch...)

**Comment by blerner** [comment]
![image](https://user-images.githubusercontent.com/918464/32812195-d73fb816-c971-11e7-8a4e-bd37e7a5764d.png)
