### ISSUE TITLE
Share dialog

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#256]
![screenshot from 2017-11-28 00-12-39](https://user-images.githubusercontent.com/9099577/33303392-f565ac1a-d3d0-11e7-9222-8f16ab314ab7.png)

A few issues:

1. Should have a fixed width of the textbox
2. The textbox should not be editable (I can replace the whole URL with something I type)

**Comment by blerner** [comment]
Item 2 isn't a major issue, since you're free to edit your address bar or your program, equally freely...

**Comment by schanzer** [comment]
Text is now properly displayed in this scenario. @sorawee , OK to close?

**Comment by sorawee** [comment]
Yep!
