### ISSUE TITLE
TypeError in JavaScript when opening shared file (might be OK)

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#257]
1. Open any shared file (e.g., https://code.pyret.org/editor#share=0Bxr4FfLa3goOV3V4NGNYWXdSaWc)
2. The console displays

![screenshot from 2017-12-20 20-59-00](https://user-images.githubusercontent.com/9099577/34237072-b2c9ccf6-e5c8-11e7-8902-cc836580aa5b.png)

**Comment by schanzer** [comment]
@sorawee this no longer shows up in CPO for this link (or others). OK to close?

**Comment by sorawee** [comment]
Yep!
