### ISSUE TITLE
CPO opening an existing file saves the current unmodified `Untitled` file

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#259]
STR:
1. Open CPO
2. Connect to google Drive
3. File -> Open -> some saved file
4. Select "In this tab"

Result: saving a blank file as Untitled, for no good reason...

**Comment by schanzer** [comment]
YES! THIS DRIVES ME BONKERS.

**Comment by schanzer** [comment]
Now that file management is never done from the editor, this feels like it should be OK to close. @blerner , do you agree?

**Comment by schanzer** [comment]
This is no longer an issue, since the current UI doesn't let you open on top of an existing tab. Closing.
