### ISSUE TITLE
image-width and image-height are buggy

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#267]
(Copied from https://github.com/bootstrapworld/wescheme2012/issues/42)

```
include image

check:
  image-width(rectangle(0, 10, "solid", "purple")) is 0
end
```

fails with "1 != 0"

**Comment by sorawee** [comment]
Totally unrelated: is it possible to create a repo that host common files in both Pyret and WeScheme, so that we need only only fix in one place?

**Comment by blerner** [comment]
This is deliberate: https://github.com/brownplt/code.pyret.org/blob/c45390ac19012d2db34a7aa15f5ee9983a7834de/src/web/js/trove/image-lib.js#L1319

**Comment by schanzer** [comment]
The files aren’t identical, sadly. But I echo Ben’s comment

**Comment by sorawee** [comment]
Well, I would say

1. It's weird from users' perspective
2. https://www.wescheme.org/openEditor?publicId=LBXSQ2aKKG is one of showcase programs in WeScheme. One of the tests in this file is `(check-expect (image-width (rectangle 0 10 "solid" "purple")) 0)`, so this is something that is expected to work before.

**Comment by schanzer** [comment]
Then that showcase file needs to be fixed. :)

IIRC, Danny originally had this produce a zero-width rectangle, and I fixed the behavior sometime in 2013.

I’ll get to this tomorrow. Either way, this issue is #wontfix, but I’m really glad you’re reviewing closely enough to find point this out!!

**Comment by blerner** [comment]
Having images of width or height zero can cause various image libraries and
file formats to crash badly (eg PNG images can't be width or height zero).
Not much we can do about that in all cases...

>

**Comment by blerner** [comment]
@schanzer `empty-scene(0, 0)` produces an image of genuinely zero width and height.  Even trying `frame(empty-scene(0, 0))` produces an invisible scene.  What should we do in that case?

**Comment by schanzer** [comment]
`2htdp/image`'s behavior seems to gave changed since 2013. I specifically made a note about this in world.js way back when, though it looks like I didn't finish the job with empty-scene.

However, this may all be moot. I just fired up DrRacket and found that a zero-height rectangle no longer shows up as a line, and that the height is indeed 0. I'm inclined to say we rip out those lines and follow suit. Do we have any evidence that things break for CPO?

**Comment by schanzer** [comment]
After testing various expressions and combinations, I don't see anything causing WeScheme to break. I think we can safely remove all the `max(1, ...)` calls

**Comment by blerner** [comment]
Good.  This is now messing with BS:Physics folks also, so I'm going to change this on the new-image-lib branch.

**Comment by schanzer** [comment]
Why leave the other lib broken?

**Comment by blerner** [comment]
Non-sequitur. Now that the new image library is merged to horizon, both the untyped and the typed image libraries run from the same underlying source, so both get the change. If you mean why didn't I fix wescheme, it's because I don't know where that source code lives...

**Comment by schanzer** [comment]
👍
