### ISSUE TITLE
[a11y] "Contribute detailed usage" UI

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#279]
On horizon with a11y, there's no text in the Pyret menu for "Contribute detailed usage". Also, clicking on the question mark for help simply checks/unchecks the box rather than giving any feedback.

![contribute](https://user-images.githubusercontent.com/119891/43087838-aad614ce-8e55-11e8-9249-acc36e07181b.gif)

**Comment by shriram** [comment]
Yikes! How the heck did this happen? Dorai?

**Comment by ds26gte** [comment]
On it. (I can confirm I didn't delete that label, but it seems to be hiding.)

**Comment by ds26gte** [comment]
PR #280 fixes this.

**Comment by shriram** [comment]
Thanks, but how did this _happen_? How'd it get dropped in the first place?

I'm really worried about things mysteriously disappearing — we don't have
the resources to manually find all such things.

**Comment by ds26gte** [comment]
It was a silent typo of a missing string delimiter on an element attribute in an HTMLfile. Unlike in JS, say, no error is signaled, HTML won't fail catastrophically, and the visual tipoff occurs on a single item deep inside a submenu. I should've use some standard HTML linting.

**Comment by jpolitz** [comment]
> I should've used some standard HTML linting.

Good criticism of the /editor page build process in general stretching way back (long before any a11y edits), and becoming more important as that markup seems to be growing quite a bit.

Would be happy to see something added to the build for checking this.
