### ISSUE TITLE
Splash page file picker is too sparse

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#297]
Right now the file picker shows icons for the files, but they're all identical. This doesn't add any new information and it doesn't look great, and it reduces information density quite a bit. 

Why not at least use a nice, dense list of files? We could add extra information such as "last modified", which (frankly) would help a lot when you have files with duplicate names.

**Comment by blerner** [comment]
Is this UI even something that we control, or is it constructed by Google?

**Comment by schanzer** [comment]
IIRC, the Google file picker lets us choose.

**Comment by jpolitz** [comment]
I think this has been fixed for a while (dense rows w/timestamps)
