### ISSUE TITLE
Logged-in username should be visible in editor

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#299]
Use-case: You're a teacher with 35 students. You want to walk by their screens and make sure they are each logged in with the right account. Right now, it’s not obvious what account is logged in just by looking at the screen. 

I know this is partially-mitigated by https://github.com/brownplt/code.pyret.org/issues/147, but I think we can do better.

**Comment by blerner** [comment]
How did we get from "definitely fixed" to "partially mitigated"?

**Comment by schanzer** [comment]
Because the original issue was that there was no way to see the logged in user. And now that’s fixed. 

This issue is about wanting that to be visible all the time.

**Comment by schanzer** [comment]
This is now visible - all the time - in the footer. Closing.
