### ISSUE TITLE
Images should display in failed test output

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#3]
This test:

```
check:
  triangle(50, "solid", "green") is triangle(55, "solid", "green")
end
```

Currently prints the test output:

```
Reason: values not equal:
[object Object]
[object Object]
```

This rendering shouldn't try to tostring() the test case directly, but should extract the values and use `renderPyretValue` (https://github.com/brownplt/code.pyret.org/blob/master/src/web/js/output-ui.js#L704) to draw the images inline (which will automatically thumbnail them, etc).

**Comment by schanzer** [comment]
This has been fixed for a while, at least for trivial cases. @jpolitz, are there still other corner cases that you'd like to keep this open for?

**Comment by blerner** [comment]
No, I think this is safe to close.
