### ISSUE TITLE
Published link UI is confusing

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#301]
[I couldn't find an issue for this, but I really thought there was one...]

Share dialog links spill out of the dialog for some reason (see screenshot). They also use `<INPUT>` elements, even though they’re read-only — so the user gets a hint that the link is editable, but then finds out it’s not. I also can’t seem to double-click on the docID to copy it: it just highlights the whole URL instead. Have we intentionally broken normal text handling behavior here?

None of this would be an issue if we used normal `<span>`s, instead of a text input.

![image](https://user-images.githubusercontent.com/77126/50026695-b320ff80-ff9e-11e8-829b-c422cb9065c9.png)

**Comment by jpolitz** [comment]
A concrete suggestion that we had recently that I like is to:

- Hide the import code by default behind an expandable [+]
- Render the share URL as a _link_ not as a textbox. This UI tries to copy what GDrive does, but it's not clear that's the best thing to do. Rendering it as a link would make folks click it, which would lead them to a (new) tab with the right URL at the top to copy/paste.

**Comment by schanzer** [comment]
@jpolitz @asolove Picking up this old thread. 

I don't like rendering it as a link. For one thing, I think consistency with Google - which everyone knows - is a virtue. What I'm wanting is the textbox to behave like a real text box, where I can select a subset of the text and then copy/paste it (into a context!). 

Right now we have the worst of both worlds: it's not a clickable link, and it looks like a textbox but then doesn't act like one. I'm guessing there's some too-clever JS behind the scenes, which could simply be deleted to give us normal textbox behavior?

**Comment by asolove** [comment]
Yeah, +1 on this should be a text input, and then next to it we should have a "copy" icon that puts the URL into your clipboard like the current behavior. I don't think that would be too hard.

If I can find a way to do it, I also like the suggestion to make the import syntax less obvious/parallel, but still present for people who want it. 

I also continue to struggle with the whole shape of this modal. It's not clear to me (still) whether the original urls still work after you press publish, and if users understand the semantics of copying link to current versus pushing a publish button to update.

**Comment by schanzer** [comment]
Closing as woefully out-of-date, esp we have newer issues that address the remaining needs (#492 , #493 #414, etc).
