### ISSUE TITLE
Publishing UI -- what do "close" and "update" mean?

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#302]
I honestly don’t know why the “update’ button exists, since it seems to be a no-op relative to “close”. I only ever see one URL when I click publish, so presumably it’s updating the same URL every time. But if I click “close” instead of update, does that mean the URL isn’t updated? So if I copy the link and send it to a friend, but then click close, my friend isn’t getting the updated file? I can't figure it out just from the UI.

**Comment by asolove** [comment]
related to https://github.com/brownplt/code.pyret.org/issues/350 and I have a request for if it's ok to fix there

**Comment by schanzer** [comment]
Closing as fixed by the merged PR
