### ISSUE TITLE
Using Resize on plots from DS 1.4 internal library 

### ISSUE THREAD

**Issue by BootstrapJen** [brownplt/code.pyret.org#305]
Using "Resize" on a scatter-plot from the DS 1.4 internal library doesn't seem to work, nor do the Zoom functions. I'm using Chrome on macOS.

**Comment by schanzer** [comment]
The internal library just uses the standard from-list.scatter-plot function. I suspect that function is where the real bug lies

**Comment by sorawee** [comment]
If you give can me actual code, I can fix it.

**Comment by BootstrapJen** [comment]
[https://code.pyret.org/editor#share=1ZQNHjN3Nmkz8gRPLkgveY7YMvTdOux3z&v=bf92f5e](Link to Animals dataset with extra code)

For example, I tried to change the x-max and y-max to 25 and 10, respectively, but nothing happens when I click "Redraw" after changing the numbers.
