### ISSUE TITLE
UI for Test result blocks

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#310]
It would be nice to have those test-result blocks either (a) take up less room or (b) be hide-able. When the # of examples blocks gets beyond 4-5, the UI fills the REPL with test-result blocks and forces the cursor to the bottom of the screen.

This is annoying when I'm teaching with a projector, and we have a teacher here who's also irked by it. This seems like a low-hanging piece of UI fruit to pick.

**Comment by blerner** [comment]
Same as #278 , closing this one since that one has a screenshot
