### ISSUE TITLE
Line breaks in 'defined twice' error

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#32]
1) open a new file, with the code:
x=4
x=5
2) click run

EXPECTED: error message listing both locations, separated by a line break, a comma, or something
RECIEVED: definitions: line 1, column 0definitions: line 2, column 0

**Comment by jpolitz** [comment]
Thanks, reported also at #540, fixed by
https://github.com/brownplt/pyret-lang/commit/800d21839fa28372c3d8a08f98be396d65b3c573,
change will show up soon.

On Tue, Aug 18, 2015 at 2:06 PM, Emmanuel Schanzer <notifications@github.com
