### ISSUE TITLE
check dark mode with table row rendering

### ISSUE THREAD

**Issue by shriram** [brownplt/code.pyret.org#335]
I'm using Monokai in the browser extension, and this code
```
t = table: x, y
  row: 1, 2
  row: 3, 4
end

t.row-n(1)
```
produces this output:
![image](https://user-images.githubusercontent.com/75030/87842794-4f973c00-c87d-11ea-835e-d32576b59806.png)
Your eyes probably have to be a lot younger than mine to see the `3` and `4` in there!

**Comment by blerner** [comment]
@thomascastleman this seems to be something for you.  I'll add that when I pull from your latest commit (https://github.com/brownplt/code.pyret.org/pull/332/commits/4c715a4fc1d86b5a3b18c47b251de349f8ca804c), I get some very odd "incomplete styles": if I start off in the default style and run Shriram's program above, I get
![image](https://user-images.githubusercontent.com/918464/87843523-3e512e00-c883-11ea-8f35-dba69f04550e.png)
If i switch to Monokai, I get
![image](https://user-images.githubusercontent.com/918464/87843507-1e216f00-c883-11ea-986a-974228b82177.png)
For some reason, the background hasn't changed, but the REPL has.  If I switch back to default I get the original image, and if I switch back to Monokai a second time, I get
![image](https://user-images.githubusercontent.com/918464/87843515-30031200-c883-11ea-85f7-6372b5832683.png)

**Comment by thomascastleman** [comment]
If Shriram is using the original extension's highlighting (dark-pyret), that was a bug I patched but forgot to roll out on the Chrome store (oops). It shouldn't be an issue in the latest themes on my `style-updates` branch though, so Ben's case is concerning.

@blerner , I seem to be unable to reproduce the issue--which browser are you using? Also, could you inspect & watch the class on the `body` as you load the page/change themes to see what's happening there?

**Comment by blerner** [comment]
Ah, never mind, that's better: I had some stale build state.  After rebuilding, I get a cleaner appearance:
![image](https://user-images.githubusercontent.com/918464/87844108-e0731500-c887-11ea-82e4-464227abecca.png)
Closing this issue as fixed in the PR, but there is a lingering issue that I'll comment on there.
