### ISSUE TITLE
When editing a new file, "Save" is disabled

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#339]
Instead, only "Save a Copy" is enabled. This actually confused me for a moment this morning, and I had to double check whether I was logged in and had somehow opened a shared file (and accidentally emptied it).

**Comment by blerner** [comment]
This was a deliberate design choice (and one I think you'd suggested), to ensure that new files can't be saved as "Untitled" every darn time.

**Comment by schanzer** [comment]
My original suggestion was that Saving a file would put up the dialog that forces them to choose a name. That seems orthogonal to whether the dialog comes from "Save" or "Save a Copy". Personally, I find the latter confusing.

Why is "Save a Copy" the only button that can bring up the dialog?

**Comment by schanzer** [comment]
@blerner poking about this. Let's talk and either (a) decide to do it or (b) close the issue.

**Comment by schanzer** [comment]
Closing, since "save" is no longer disabled
