### ISSUE TITLE
Add "grey" in addition to "gray"

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#351]
We have a few teachers from Jamaica who grew up with the British spelling. Any chance we can support both vowels?

**Comment by blerner** [comment]
IIRC we had tried to _eliminate_ synonyms for colors to simplify the color namespace.  Do we really want to reintroduce them?

**Comment by schanzer** [comment]
I don't see this as a synonym, as much as an alternate spelling. I know there were lots of other colors we took out ("pink" v. "lightred"), but this seems like a different issue.

**Comment by shriram** [comment]
Agreed. It's just a matter of "this color isn't in the language" for them.

**Comment by blerner** [comment]
Agreed with which?  Your comment could equally well apply to either of our statements so far ;-)

Also, if you want to go this route, do you intend to have respelled synonyms for light-gray, gray, dark-gray, and dim-gray?

**Comment by shriram** [comment]
I'm agreeing with Emmanuel. There is no canonical spelling for this color,
so we'd have to have both spellings.

**Comment by schanzer** [comment]
@blerner is this something we can add easily?

**Comment by blerner** [comment]
It's slightly annoying, but it's doable.  Again: do you want to double-spell every variant of gray, light-gray, dark-gray and dim-gray?

**Comment by schanzer** [comment]
Yes

**Comment by schanzer** [comment]
Updated WeScheme to match in bd515eee789f929dae4a46387d0fc75bd066ba6b
