### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by danilbraun** [brownplt/code.pyret.org#353]
`The command "if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then heroku local:run node_modules/.bin/mocha; fi" exited with 2.`

**Comment by jpolitz** [comment]
Thanks for reporting! Can you say a little more about where this is happening? Is it on a fork through Travis, on your local machine, etc? Which commands did you run to start the build?

**Comment by danilbraun** [comment]
I haven't tried to build it myself, I just saw the badge ![](https://camo.githubusercontent.com/824b5b449b9b79173541e832104a587cdbd271975ee1ad8e4b02f954b23aab2f/68747470733a2f2f7472617669732d63692e6f72672f62726f776e706c742f636f64652e70797265742e6f72672e737667). CPO can be built despite what is written on the badge?

**Comment by jpolitz** [comment]
It can be locally, BUT you've also pointed out another issue that looks like an npm version incompatibility. Oops. That I'm working on fixing now.

**Comment by danilbraun** [comment]
@jpolitz and is there a way to deploy it (and examplar) on a hosting other than heroku?

**Comment by jpolitz** [comment]
Are you really stuck on something? I’m confused about how Heroku is involved — this error is a Travis build. Do you need help with a particular deployment? Maybe best to take it to email? joe.politz@gmail.com

**Comment by jpolitz** [comment]
In any event, I think this is resolved now! Thanks for pointing it out, there were several annoying-but-fixable issues compounding here. I hope this didn't stop you from doing your work!
