### ISSUE TITLE
Chart: JS error 

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#354]
Consider an example from the doc:

```
include chart
import color as C

fun some-fun(x): num-sin(2 * x) end
a-series = from-list.function-plot(some-fun)
  .color(C.purple)
a-chart-window = render-chart(a-series)

a-chart-window
  .title("a sine function plot")
  .x-axis("this is x-axis")
  .y-axis("this is y-axis")
  .display()
```

which produces a JS error (shown in the red box):

<img width="400" alt="Screen Shot 2020-11-28 at 14 13 52" src="https://user-images.githubusercontent.com/9099577/100527100-1902f380-3184-11eb-8b5e-42c98869ed2f.png">

This is because when we use `.title(...)`, the DOM changes, which breaks:

```
          // HACK(Emmanuel): 
          // The only way to hijack marker events is to walk the DOM here
          // If Google changes the DOM, these lines will likely break
          const svgRoot = chart.container.querySelector('svg');
          const markers = svgRoot.children[2].children[2].children;
```

CC: @schanzer

**Comment by schanzer** [comment]
Oh, poop. Will look into this.

**Comment by schanzer** [comment]
Spent a little time on this today. @jpolitz [this line](https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/trove/chart-lib.js#L662) includes the word "if", yet there's no code anywhere that checks to see "if" images are defined for these datatpoints. I'm tempted to check if the elements in `combined` have a length of 4, and use that to determine whether [this new code](https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/trove/chart-lib.js#L666-L694) is run at all.

Does this seem kosher to you?

**Comment by jpolitz** [comment]
Yeah I think we should be able to lift `hasImage` to outside this map ( https://github.com/brownplt/code.pyret.org/blob/9e9c70b8cf6e95d8d580c7233d9a7e07644841a6/src/web/js/trove/chart-lib.js#L519 ) and then use it consistently where we need guards (in particular, before registering the 'ready' handler you link to).

**Comment by schanzer** [comment]
@sorawee and @jpolitz , the (tiny) fix is ready for review and merge at your discrection
