### ISSUE TITLE
Is the ARIA labelling for rotations backwards?

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#356]
`rotate(27, ellipse(40, 20, "solid", "gray"))` produces a value whose `aria-label` attribute is `"Rotated image, -27 degrees:  a solid gray ellipse of width 40 and height 20"` -- note the minus-sign in the degrees.  @schanzer @ds26gte your input would be useful here :)

**Comment by schanzer** [comment]
Isn't the default rotation behavior CCW?

**Comment by blerner** [comment]
Yes, but I'm surprised at the mismatch between the argument `27` and the description `-27 degrees`

**Comment by jpolitz** [comment]
I think that commit is just the initial commit of image.js, that mirrors the original, API-edited to match how the Pyret module works (see https://github.com/bootstrapworld/wescheme/blob/742326520bc7b4b4ad2d30d4273b43b0ced2f7f6/war-src/js/js-runtime/primitive.js#L5366)

It seems like the internal API and the user-facing API use degrees in different “directions.” The aria-text speaks negative in both WeScheme and CPO.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/119891/100660399-d3baff00-3306-11eb-8d14-7aabf6cd0523.png">

Agree with @blerner that we should re-invert the argument when spoken (and probably consider doing the arithmetic inside the `RotateImage` methods)

**Comment by schanzer** [comment]
I'm convinced - negating the angle for ARIA is the right move. WeScheme will be updated tonight.
