### ISSUE TITLE
Dark mode selection in the REPL is mostly invisible

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#363]
I've highlighted "methi" in the screenshot below.  Can you see it?
![image](https://user-images.githubusercontent.com/918464/103145366-3b4a4b80-4707-11eb-8a40-760f93f60468.png)

**Comment by jpolitz** [comment]
Yes, but I’m proud of myself for doing so. Confirming this is an issue :-)

**Comment by shriram** [comment]
I only saw it after Joe said he could see it. (-:
