### ISSUE TITLE
Design a theme that is friendlier to color-blindness

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#382]
Now that we have theming support, it should be easier to manage this.  The distinctions between blues/purples, or purple/red, seem not to have been visible enough to some teachers.  I'll try to get some more feedback from teachers which ones they had the most trouble discerning.

Pinging @thomascastleman (for themes), @schanzer and @ds26gte (for accessibility)

**Comment by schanzer** [comment]
Worth looping in @asolove as well, since I know this is something he's thinking about in his UI revamp.

**Comment by thomascastleman** [comment]
Great--with the theming we have it should be relatively straightforward to create a new theme (just make a copy of [the template](https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/css/themes/template.css) and choose new colors). 

We could also start from another theme already in use and work off of that, which might make more sense if only certain parts are in need of color changes.

**Comment by blerner** [comment]
A suggestion was made by one teacher to rely more heavily on font changes, rather than solely color changes. For instance, our incomplete and complete string literals are distinguishable even with red/green color blindness, because they also change boldness. We should consider bold, italic, and possibly font-size changes as well.
