### ISSUE TITLE
typing multiple lines at REPL causes prompt height to expand

### ISSUE THREAD

**Issue by thomascastleman** [brownplt/code.pyret.org#387]
Try typing in this check block at the REPL:
```
check:
  1 is 1
end
```
(it's important that you type it in--copying and pasting does not get the same effect). Notice the REPL prompt grows downwards as you type:

![large-prompt](https://user-images.githubusercontent.com/13399527/126879623-02dfbc99-3805-4b9c-b59d-c71fce74a22b.png)

From what I can tell in dev tools it seems the `.CodeMirror-lines` div that is containing the code has a `padding-bottom` that is being repeatedly added to. I am not sure why however.

**Comment by jpolitz** [comment]
Confirmed. But 🤔🤔🤔.

I have no idea what's going on. I don't see relevant changes to
pyret-codemirror-mode or CPO (which in any event has deployed in a while,
waiting for a significant summer update)

**Comment by asolove** [comment]
👀 have a theory on this, will send a PR shortly
