### ISSUE TITLE
Hovering over multiple test cases flashes the red indicator many times

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#4]
When moving the mouse over the test results, if it moves over several that are off-screen, the red "offscreen" indicator flashes many times.  It ought to not re-flash if it's already in the middle of it's animation, because if you trigger a dozen flashes, it can sit there flashing even when the mouse has been moved away.

**Comment by schanzer** [comment]
The error behavior has changed such that this Issue no longer seems to apply. Suggest closing.

**Comment by shriram** [comment]
@jswrenn Please confirm and close.

**Comment by schanzer** [comment]
@shriram Still not an issue, 3 years later. Jack is gone, but OK to close?

**Comment by jswrenn** [comment]
Happy to do the honors. :-)
