### ISSUE TITLE
Font size picker can wrap

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#405]
I saw this in an embedded context (when on an iframe in VMT), but it doesn't look great:

![image](https://user-images.githubusercontent.com/119891/135512826-89a81faf-e95b-42e6-9b16-7709e1445200.png)

**Comment by sorawee** [comment]
Also, let me repeat the issue I raised at https://github.com/brownplt/code.pyret.org/pull/377#issuecomment-847822736, in case they can be fixed together.

> The font size controls in the main menu are greyed out, making it look like the controls are disabled. However, they actually are not. The situation is slightly better in master because when you hover over it, the color changes. In horizon, the color doesn't change at all on hovering.

**Comment by asolove** [comment]
I intend to open a PR shortly to:
- Prevent wrapping
- Make the buttons clearer (no gray!)
- Prevent weird font sizes with long decimals

**Comment by asolove** [comment]
This is fixed as part of #434 .

**Comment by schanzer** [comment]
Closing, since the PR was merged and the font size picker no longer wraps
