### ISSUE TITLE
'targetOrigin' not initialized when handling web events

### ISSUE THREAD

**Issue by anzook** [brownplt/code.pyret.org#407]
Pyret editor error due to 'targetOrigin' not being initialized within events.js (possibly POSTMESSAGE_ORIGIN is undef)

![Screen Shot 2021-11-06 at 11 21 13 PM](https://user-images.githubusercontent.com/56008225/140632094-5c2f6a14-3aa4-43ab-ab76-4772eefe0044.png)

Currently experiencing the error when trying to use the editor as an embedded iFrame (no error on standalone editor), such as within [vmt](https://vmt-test.mathematicalthinking.org/myVMT/rooms/6184218d5293020996d03c9d/details). Error occurs and is visible in console logs on any user event within the embedded editor.

I was not able to get a local (:5000) host build running to test and diagnose, but I will update as I'm able.

**Comment by jpolitz** [comment]
Thanks! I'm not sure how this worked in testing; the setting of `POSTMESSAGE_URL` was happening too late. Fixed by https://github.com/brownplt/code.pyret.org/commit/b6036e53736fcf0e547bf80d9c2965265919fcc9

**Comment by anzook** [comment]
Confirmed working in partner app with the fix in deployment! Thanks
