### ISSUE TITLE
Allow for color selection in various charting functions

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#412]
See https://pyret.slack.com/archives/C156F5GGP/p1629782547014200

This is pretty important from a Bootstrap curriculum use-case. When analyzing a dataset of animals, for example, students get _really_ tripped up when dogs are blue in one pie chart and green in another.

**Comment by blerner** [comment]
Being addressed by #421, correct?

**Comment by schanzer** [comment]
Confirmed - this should be closed once that is merged

**Comment by schanzer** [comment]
Closing now that it's merged
