### ISSUE TITLE
Load CodeMirror's runMode

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#43]
Every time I open the console I will see messages "Uncaught TypeError: CodeMirror.runMode is not a function". This is because `runMode` is a CodeMirror's add-on, and it's not loaded automatically.

And, even though we manage to load `runMode`, it will still not work. The third parameter to `runMode` must be a callback, but `echo` is not.

**Comment by belph** [comment]
> And, even though we manage to load runMode, it will still not work. The third parameter to runMode must be a callback, but echo is not.

Not true. If you pass in a DOM node, CodeMirror will make a function out of it ([source](https://github.com/codemirror/CodeMirror/blob/master/addon/runmode/runmode.js#L19)). There is a problem, though, an that is the selector for `echo` is returning an array of length one. By passing `echo[0]` to `runMode`, the behavior works as desired.

**Comment by sorawee** [comment]
I see. Yesterday I did exactly what you did except the `echo` part where I get a TypeError, and I couldn't figure out how to continue. Thx for fixing this!
