### ISSUE TITLE
Save button in Interactive Charts has no alt-text

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#439]
We have a teacher here who has a student who uses screenreaders, and he _immediately_ pointed out that a screenreader has nothing to say for this button. 

Small fix. Would be awesome to show him it's fixed before Friday. :)

**Comment by jpolitz** [comment]
Pushed to main site. Thanks for reporting – LMK if it works for him (added `title` and `alt` and tested with VoiceOver)

**Comment by schanzer** [comment]
He wrote back _tonight!_ Totally impressed. 

THANK YOU FOR MAKING US LOOK AMAZING!
