### ISSUE TITLE
Can unstyled errors wrap?

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#446]
This has been an issue for some time, and I swear I've reported it before. But I can't find an open issue, so hopefully this isn't a dupe.

Unstyled errors currently don't respect line wrapping:
![image](https://user-images.githubusercontent.com/77126/180472531-81df1c5e-a88e-4ec3-baf4-d88ceafd1940.png)

There's currently a CSS rule that says whitespace inside `.replTextOutput` must have `white-space: pre`. This is what's stopping it from wrapping. I'm guessing this is to help the display of big structures from wrapping, which would be totally annoying. :-)

Could we perhaps use a more surgical rule for this? I notice that all the styled errors have the class `highlights-active`, and all errors have `compile-error`. So a rule that ONLY affects unstyled errors would be...

`.compile-error.not:(highlights-active) .replTextOutput { white-space: normal; }`

**Comment by blerner** [comment]
No.  I'm betting you're doing `raise("foo")` and getting that output, because `raise` raises a Pyret value...

... or an actual error value.  Try `include errors` and then `raise(message-exception("hi"))` instead: that'll simply render the string directly as text.

**Comment by schanzer** [comment]
Beautiful. Thanks!
