### ISSUE TITLE
Modal popup can be moved so that the close button is inaccessible 

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#470]
<img width="325" alt="image" src="https://github.com/brownplt/code.pyret.org/assets/77126/2df7c045-004a-4e7b-b781-ce0e5f6d00e3">

We had a teacher get totally stuck and flustered when she couldn't get the `x` back. jQuery has about a million settings for stuff like this -- is there any setting to disallow moving the modal off the left-hand and top edge of the screen?

**Comment by schanzer** [comment]
This **destroyed** me in PD today. If you zoom in (to show people a chart more closely), and then zoom out, some state in jquery gets is screwed up to the point where all new pop-ups will appear off screen. And I don't just been a little off screen -- I mean so far off screen that you can't see them, move them, or close them.

If there's a sequence of important things in the interactions area, refreshing is not an option - So all charts are useless.

**Comment by asolove** [comment]
@schanzer can you send me a set of steps to reproduce this? I can't tell what model you're in from that screenshot. And the one I tried (insert image) seemed to be ok post-zoom.

**Comment by schanzer** [comment]
@asolove !! thanks for looking into this. It took me a few minutes to remember the sequence that replicated it. 

1. I was only able to replicate this in Firefox, though I could have sworn the teachers in July were using chrome...
2. Load a pyret file ([this is the one I used](https://code.pyret.org/editor#share=17266_Kczy0pJxp8TzkMsawaMavG4PDpk)), and click Run.
3. Generate a chart in the interactions area (`pie-chart(animals-table, "species")`). It opens in a sensible location! 
4. Close the chart, then zoom in _using a pinch gesture_ (NOT `cmd +`!!). Zoom out _using a keyboard shortcut_ (`cmd -`!) so that everything appears to have gone back to the same size
5. Regenerate the same chart. It opens off the edge of the screen! Sometimes you can even get it to hide the entire drag bar!

**Comment by schanzer** [comment]
@asolove I haven't opened FF in a while, and after writing that I noticed that it was asking me to upgrade to a later version. It looks like I can't replicate the issue anymore in the latest release, so I'm wondering if this is something that was also broken on Chrome in July but has since been fixed.

We can likely close this.
