### ISSUE TITLE
Save as

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#48]
Currently, the semantics of changing a filename is to rename the existing file.

This is consistently confusing for users.  A better flow is probably:
1. Changing the name and clicking "Save" creates a new file.
2. More... has an option for explicitly renaming the file (or even the file has to be renamed in Drive, since this is much less frequently necessary)

**Comment by sorawee** [comment]
I disagree. Take OS X's Finder as an example. Changing the name means renaming, not creating a new file. I think the new semantics is even more confusing.

If we want to make it clear, perhaps we should make the textbox at the header uneditable. The save button stays the same. Then, add two items to the menu: "Rename" and "Clone to a new file".

**Comment by schanzer** [comment]
Now that these menu items have been added, is this OK to close?

**Comment by schanzer** [comment]
@jpolitz OK to close?
