### ISSUE TITLE
Chart package: residuals

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#486]
### Note: Algebra 2 is blocked on this feature

Long story short: Bootstrap's algebra 2 materials rely on the ability to quantitatively compare the fitness of different models, in order to motivate students to use quadratics, exponentials, logarithms, etc to find the best-possible fit. We originally relied on R^2 for this, since it's the only quantitative comparator we have. @shriram  and Nancy Pfenning correctly pointed out that in doing so, _we've essentially set kids up to become bad data scientists_: "find the best R^2 you have and you've got a correlation!"

We need a different quantitative measure of fitness that doesn't immediately leap to value judgements about correlations, and Nancy proposed _residuals_ as the way to do it. I think this is spot-on, as it both solves all of our immediate problems for Algebra 2 and opens up important content we'd like to cover anyway in Data Science.

**Comment by jpolitz** [comment]
Notes from a recent meeting – we need the ability to have something that gives custom labels on the scatter dots (right now they'd just show the actual number, not the residual, if you used https://pyret.org/docs/latest/chart.html#%28part._chart_render-charts%29).

So some help from the JavaScript chart library would be needed here.

**Comment by jpolitz** [comment]
The implementation of `residuals` is straightforward:

```
fun residuals(xs, ys, f):
  for map2(x from xs, y from ys):
    f(x) - y
  end
end
```

**Comment by jpolitz** [comment]
@ds26gte this PR is a useful place where we added a new chart type/primitive:

https://github.com/brownplt/code.pyret.org/pull/456

**Comment by jpolitz** [comment]
This single commit may be useful to see: https://github.com/brownplt/code.pyret.org/pull/456/commits/e637c3dee1b1056bbd5245323128439608c1248c

Also this PR for box-plot: https://github.com/brownplt/code.pyret.org/pull/244/files

**Comment by jpolitz** [comment]
Probably the spec here is to create a new chart type called `residual-chart` that takes a list of xs, a list of ys, and a list of residuals.

It renders vertical bars from the y locations in correct proportion for the magnitude of the residual. (The black bars in @schanzer 's picture)

**Comment by schanzer** [comment]
Adding notes from my call with @ds26gte 

- Google Charts _already has an [interval chart](https://developers.google.com/chart/interactive/docs/gallery/intervals)_, which can be configured to draw intervals as lines, error bars, area charts, and more. 
- Dorai is going to try and use this built-in chart to draw the bars. If successful, there's no SVG hacking necessary and we let Google's library do all the work instead of us. Win!
- If this is feasible, Pyret would gain an `interval-chart` API, which could potentially be configured to draw many kinds of intervals and used for a wider array of purposes.

**Comment by ds26gte** [comment]
Please see & review my PR for this. I've called the chart type `interval-chart` since it seems like a more abstract name for this possibly reusable chart type. The user-facing function is `from-list.residual-chart(xs, ys, residuals)`, where all three args are lists of numbers. 

(I've made the residuals the alternate ordinates after reviewing the requirements orally with @schanzer. But it now looks like we actually want them to be the +/- offset from the y. This can be easily ironed out once we're satisfied with the rendering.)

**Comment by schanzer** [comment]
@ds26gte there's one more use-case that I don't think we tested, which is composing an interval chart with another kind of chart (say, a function plot or a scatter plot). Modifying your test example to use `render-charts` (plural) exposes a missing method:
```
include color
include chart
include image

# Constants

xs = [list: 1, 2, 3, 4, 5]
all-ys-rough = [list: ~1.2, ~4.9, ~8.88, ~15.76, ~23.3]
all-ress-rough = [list: ~+1.23, ~-2.9, ~+3.29, ~-4.02, ~+5.67]

ser-all-ys-all-ress-rough = from-list.interval-chart(xs, all-ys-rough, all-ress-rough)

# Helper function

fun render-image(series):
  render-charts([list:series]).get-image()
end
```

![image](https://github.com/brownplt/code.pyret.org/assets/77126/9fbc4802-5cc0-4eb3-a7cf-36e8047a2fbc)

To be honest, this is a corner of the chart package that I've essentially copy/pasted without fully understanding. You may need to ask @jpolitz for clarification.

**Comment by jpolitz** [comment]
It seems like `render-charts` assumes the charts are all either `scatter-plots` or `line-plots` (it uses "partition"). I wonder if @sorawee knows more.

https://github.com/brownplt/code.pyret.org/blob/b745daeeb06096985b056dc1965e7fe2a357f56d/src/web/arr/trove/chart.arr#L2457

Should test with more kinds of charts, etc. This logic might just be stale and not well-tested for various combinations.

**Comment by sorawee** [comment]
Right. The doc specifies:

> All [DataSeries](https://pyret.org/docs/latest/chart.html#%28part._chart_.Data.Series%29) in lst must be either a [function-plot-series](https://pyret.org/docs/latest/chart.html#%28part._chart_function-plot-series%29), [line-plot-series](https://pyret.org/docs/latest/chart.html#%28part._chart_line-plot-series%29), or [scatter-plot-series](https://pyret.org/docs/latest/chart.html#%28part._chart_scatter-plot-series%29).

This is because (at the time), it only makes sense to render these three things together. They all have compatible axes. It doesn't make sense, for example, to render a pie chart along with a scatter plot in the same window.

**Comment by schanzer** [comment]
OK, so there's a list of things that will need to be done to compose interval-charts:

- [ ] update the [relevant docs](https://pyret.org/docs/latest/chart.html#%28part._chart_.Data.Series%29)
- [x] add interval-charts to [the `render-charts` code](https://github.com/brownplt/code.pyret.org/blob/b745daeeb06096985b056dc1965e7fe2a357f56d/src/web/arr/trove/chart.arr#L2457) that looks for partitions
- [x] add a partition field to the [default-interval-chart-series](https://github.com/brownplt/code.pyret.org/blob/b745daeeb06096985b056dc1965e7fe2a357f56d/src/web/arr/trove/chart.arr#L1062-L1072), similar to [how it's done for the default-scatter-plot-series](https://github.com/brownplt/code.pyret.org/blob/b745daeeb06096985b056dc1965e7fe2a357f56d/src/web/arr/trove/chart.arr#L1662)

**Comment by schanzer** [comment]
@ds26gte this looks GREAT! Have you updated the documentation to match?

@jpolitz this is definitely a high priority to get on CPO, as algebra 2 is blocked on it

**Comment by schanzer** [comment]
@jpolitz Dorai's recent fixes on the [interval-charts-improvement branch](https://github.com/brownplt/code.pyret.org/tree/render-charts-improvement) do exactly what we need. He's going to push another small update that adds a `legend` field to interval charts, but this is essentially ready for your final review.

**Comment by ds26gte** [comment]
The branch name is actually `render-charts-improvement`.

(Please note this is no longer a PR from my fork. It's a branch in `brownplt/code.pyret.org`.)

It now allows the ability to added `.legend` to interval charts.

**Comment by schanzer** [comment]
@jpolitz we're ready to rock!

**Comment by jpolitz** [comment]
Is there a pull request for me to review?

**Comment by jpolitz** [comment]
Oh it's a branch I see – making a PR from that branch to `horizon` out to work!

**Comment by schanzer** [comment]
@ds26gte rocked this -- closing
