### ISSUE TITLE
essentials2021 context now exports e

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#506]
I’m getting lots of errors related to the constants library, in files that previously worked:
![image](https://github.com/brownplt/code.pyret.org/assets/77126/fc9d46dc-af9d-4ad5-84fd-69a926205a17)

I know y'all have been working on the `starter2024` context, and adding `e` is one of the todo items. But _this_ file uses `essentials2021`. Is it possible you accidentally made this change in a way that effects old contexts?

**Please note that this breaks all of Bootstrap:Algebra for all 2023 teachers, since all the starter files use this particular teachpack**

See https://github.com/bootstrapworld/curriculum/issues/1792

**Comment by jpolitz** [comment]
Closing – fixed in teachpack by using `import constants as C` and then referring by field name. `include` considered harmful?
