### ISSUE TITLE
Can HTML entities also be replaced?

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#508]
In `text-handlers.js`, it looks like there's a list of unicode characters that get auto replaced when pasted into CPO. I'm trying to paste text from an auto-generated workbook page that contains a lot of `&ZeroWidthSpace;`.

These show up as red dots in CPO:
<img width="525" alt="image" src="https://github.com/brownplt/code.pyret.org/assets/77126/20e23bb1-f1e5-44e7-8ebc-2a3d2ac2925a">

Can we detect and replace HTML entities like this, or do they have to be unicode?

**Comment by asolove** [comment]
We can remove these. I think I know how, but can you send me some sample input (maybe as hexdump?) so I can test on it? (I don't think in the end this has anything to do with html entities, it's just checking for non-visible code points in the pasted string, and we can deal with that.)

**Comment by schanzer** [comment]
Pasting the text into my text editor revealed the characters:
<img width="1130" alt="image" src="https://github.com/brownplt/code.pyret.org/assets/77126/6ec08a58-3139-415a-97df-1b586008201e">

The attached file includes the following, showing html entities:

`fun f&#8203;(&#8203;x&#8203;): (&#8203;5613.67 &#8203;* x&#8203;) &#43; -83616.02 end`

[model-college-v-income-1.txt](https://github.com/brownplt/code.pyret.org/files/14442108/model-college-v-income-1.txt)
