### ISSUE TITLE
JsworldDomError leaks through if to-draw handler returns a non-image

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#53]
TO REPRODUCE:
```include world
fun draw-world(current-world): 0 end  
fun next-world(current-world): 1 end

big-bang(0, [list: on-tick(next-world), to-draw(draw-world)]
)
```

EXPECTED:
Something vaguely readable by humans

ACTUAL:
JsworldDomError: expected a Text or an Element, received [object Object] within [object HTMLSpanElement], [object Object]

**Comment by schanzer** [comment]
This has improved substantially (see attached image), but I suspect the error could be more clear and perhaps even highlight the `to-draw` handler name in the big-bang or reactor expression?

![image](https://cloud.githubusercontent.com/assets/77126/17902267/a435ba18-6934-11e6-99f5-7774c7fbad7b.png)

**Comment by jswrenn** [comment]
This is a more general issue with annotations (that's exacerbated when builtins are involved):
```
fun foo(a :: (Number -> Number)) -> Number:
  a(1)
end

fun bar(a :: Number) -> String:
  num-to-string(a)
end

# The annotation of `foo` isn't being met by `bar`
# The error the user gets, however, is caused by `a(1)`
# and points out the return type annotation of `foo`.
#
# The problem isn't 'the value "1"' as the error message states,
# but rather the value of `bar`.
#
# Another bug: the value "1" was not
# "sent from around" `foo(bar)`
foo(bar)
```

**Comment by sorawee** [comment]
@jswrenn just curious, do you intend to post the above comment somewhere else?

**Comment by schanzer** [comment]
Confirmed fixed on CPO
