### ISSUE TITLE
something broken in wait screen animation?

### ISSUE THREAD

**Issue by shriram** [brownplt/code.pyret.org#537]
On vanilla Brave, 1900x1200 screen, full-size window:

![image](https://user-images.githubusercontent.com/75030/76855464-93265e80-6827-11ea-8bd6-e273ae10f681.png)

**Comment by blerner** [comment]
@asolove was this one of the things you'd fixed a while back?  If so, feel free to close out this issue.

**Comment by asolove** [comment]
Yep! It's fixed now. (But I'm not an admin here, so I can't close it myself.)
