### ISSUE TITLE
Support for Grading tools in CPO

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#58]

**Comment by awstlaur** [comment]
There is _some_ progress that @fgoodman started and I fixed a small issue with and put up here: [https://pyret-grading.herokuapp.com/grade](https://pyret-grading.herokuapp.com/grade)

**Comment by awstlaur** [comment]
As a note, I am doing a lot of work on this between now and Monday to catch up with the major changes that landed in both CPO and pyret-lang this summer.

**Comment by awstlaur** [comment]
@schanzer See [TM 031: Automated-Grading-Support](https://github.com/brownplt/pyret-lang/wiki/TM-031:-Automated-Grading-Support) in the pyret-lang wiki.

**Comment by jswrenn** [comment]
@awstlaur It would be optimal to have the fancy renderings of errors and test results, because it's what students are used to. Supporting this in a modular way is a matter of moving the error-related things out of `output-ui.js` and into `error-ui.js` (where they probably belong, anyways).

Are you going to be back hacking on this anytime soon? I could do that refactoring.

**Comment by awstlaur** [comment]
@jswrenn In the context of data being stored as ascii/json files, what would the fancy renderings look like? If it's a mess of html, then it _might_ not be very useful for a course staff. (Though, if that html ends up being rendered in an email, then it might once again be useful?)

I'll be working on this (and defining/building a [checker api](https://github.com/brownplt/pyret-lang/wiki/TM030:---Check-Results-API)) over winter break.

**Comment by awstlaur** [comment]
@jswrenn I've started looking into making a checker api. Based on cursory experimentation, it seems like there is some useful functionality in `output-ui.js` that would be good to have from the `pyret-lang` side of things. Let me know how much time you can devote to that refactoring in the coming weeks.

**Comment by jswrenn** [comment]
@awstlaur What needs moving?

**Comment by awstlaur** [comment]
@jswrenn The biggest roadblock I'm having to getting the fancy renderings is mapping srclocs to asts, as is done by the output of `makeMaybeLocToAST`. I tried writing a Pyret version, as below, but ran into cyclic module problems when using it from `checker.arr`:  `checker => file => base => checker`. I'll have to do some re-organizing anyway so it may end up working later.
```pyret
import file as F
import parse-pyret as P
import srcloc as SL

fun srcloc-to-maybe-ast(loc :: SL.Srcloc):
  cases(SL.Srcloc) loc:
    | builtin(_) =>
      none
    | srcloc(filename,start-line,start-col,start-char,end-line,end-col,end-char) =>
      set-line = string-repeat("\n", start-line)
      set-col = string-repeat(" ", start-col)
      actual-code = string-substring(F.file-to-string(filename), start-char, end-char)
      faux-code = set-line + set-col + actual-code
      some(P.surface-parse(faux-code, filename))
  end
end
```

**Comment by schanzer** [comment]
Given the progress that's been made on this front (though in a different way), is this issue still something we want to keep open?

**Comment by shriram** [comment]
I don't think it needs to be in CPO. It would be nice at some point to bless and formalize @jswrenn's work (before he graduates!).
