### ISSUE TITLE
UI for the Type-Checker

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#59]

**Comment by schanzer** [comment]
@shriram IIRC this was an issue you asked me to write up during an all-hands. Is it still something we need to keep open?

**Comment by shriram** [comment]
Sorry, what is the "issue"? All I see in your original comment is "No description provided".

But given that that isn't actionable, I guess we should just close this? Unless you can tell me what the original comment was.

**Comment by schanzer** [comment]
I was hoping you might tell me what the comment was. But since you can’t, I’m closing.
