### ISSUE TITLE
Syntax coloring

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#65]
The CM mode for pyret does a good job of tagging relevant syntax for styling, but right now all the colors (with the exception of comments) are so similar that I honestly didn't _realize_ they were different! 

The most common whiteboard marker colors (in descending order) are: black, blue, green, red, orange, purple.

I'd advocate strongly for keyword, variable, function-name, etc to be black, number literals to be blue, strings to be green and boolean literals to be dark-red.  Personally, I like orange for comments (it stands out less than everything else), but purple would be fine for this as well.

**Comment by blerner** [comment]
Surely keywords ought to be different than identifiers!  Or else how would you tell them apart?

**Comment by schanzer** [comment]
There's definitely reason to differentiate them (and others), but we're loosely constrained by the set of common markers in a classroom. I'd be all for using similar colors or shades for these situations, so that they're visibly different onscreen but can be reasonable subsumed under on color when a teacher writes on the board.

FWIW - right now I can't tell them apart anyway. :)

**Comment by schanzer** [comment]
Proposal, based on the color palette of common whiteboard markers:

Keywords are black
Identifiers are dark gray
Numbers to be blue 
Roughnums are lighter-blue
Strings are green
Booleans are red
Comments are orange

Anything I'm missing?

**Comment by blerner** [comment]
unterminated strings or comments?

I know we're constrained by whiteboard markers, but man, that's an ugly color palette to be stuck with :(

**Comment by schanzer** [comment]
Heh. I'd say unterminated _anything_ should be bright red. Booleans should be dark red anyway, so as not to appear "scary".

**Comment by blerner** [comment]
Here's a potential color scheme, showing what the colors look like both normal and when highlighted:
![ss1](https://cloud.githubusercontent.com/assets/918464/15197098/95b1aa62-179d-11e6-8d29-f03c347e308a.png)
If you like it, I'll commit it and we'll be all set.

**Comment by schanzer** [comment]
I LOVE it. Holy crap yes plz.

**Comment by sorawee** [comment]
Seems that in `check` block, after the results are reported, the syntax highlight will be off.

Before Running:

<img width="564" alt="screenshot 2016-05-13 00 45 12" src="https://cloud.githubusercontent.com/assets/9099577/15238286/4e30b8ec-18a4-11e6-8f98-06560fe90302.png">

After Running:

<img width="572" alt="screenshot 2016-05-13 00 44 41" src="https://cloud.githubusercontent.com/assets/9099577/15238289/57e315ba-18a4-11e6-9595-ccca1e848ab0.png">

**Comment by blerner** [comment]
That's a deliberate feature of Jack's rendering of check blocks, and has nothing to do with this issue.

**Comment by blerner** [comment]
Whups, hit wrong button.  Will close when horizon merges...

**Comment by sorawee** [comment]
Sure, but what's the rationality for deliberately turning off syntax highlighter?
