### ISSUE TITLE
Fuzzy highlighting?

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#66]
<img width="634" alt="screen shot 2016-04-21 at 1 46 57 pm" src="https://cloud.githubusercontent.com/assets/119891/14718982/a2dca6fa-07c7-11e6-8c49-bcf2d01d4ad4.png">

Some new highlighting rule (maybe to do with matching keywords) seems to be making words look "fuzzy," like there's some alpha gradient to white on the edges?

Not sure what change made this happen, but it's kind of disconcerting.

**Comment by jpolitz** [comment]
(This is on horizon, not on CPO proper)

**Comment by blerner** [comment]
It's this: https://github.com/brownplt/code.pyret.org/commit/d220a2df702f22311e08f96e7630cb8e55d9dae3#diff-5828ef0df6fd1cbf728e4103df9b1affR69.  Turning off that one rule fixes the fuzziness, but also makes the lines appear separately highlighted.  Problem is every single token is its own `<span>` with its own box shadow, and they overlap.  This might be a partial solution: http://blog.dudak.me/2014/css-shadows-under-adjacent-elements/, but because CM sets a z-index on every row, this will only fix side-to-side overlap, not top-to-bottom overlap.

**Comment by jpolitz** [comment]
Also, changing the box-shadow to `border: 1px solid hsl(220, 100%, 95%)` seems to fill in the extra space between lines, if that's the goal.

**Comment by jpolitz** [comment]
The other issue I see is that it looks like there's supposed to be a box around `fun` and `end`, but no amount of z-index muckery makes it show up.  Is this a feature-in-progress?

**Comment by blerner** [comment]
Using a full `border` works, but it mucks with the horizontal spacing.  Using only `border-top` and `border-bottom`, though, works better.  I think the partial boxes around `fun` and `end` are actually deliberate -- they're a top-left marker and a bottom-right marker, so they shouldn't be full boxes.  Those look good to me.

**Comment by jswrenn** [comment]
Definitely a feature in progress. I needed to distinguish the block matching highlight from the error highlights. The fuzziness, as you guys figured out, was an attempt at dealing with the spaces between lines (although the fuzziness doesn't interact with text nearly as much on my machine; your screenshot looks awful). 

I like the `box-shadow` edge-fuzziness as a distinguishing feature, but not if it wreaks havoc on the visibility of the code. `border-bottom: 2px hsl(220, 100%, 95%);` seems to work for me; can you guys confirm it doesn't much with spacing for you?

The pseudo-element solution to `box-shadow` overlapping adjacent siblings is a bit tricky to get right. I'll revisit it soon, but for now I suggest we just use `border` to fill the gaps.

**Comment by jpolitz** [comment]
1px of border bottom works in Chromium (OSX) for me.  Do you need the 2px?

Thanks for pointing out border-bottom; just using `border` like I suggested clearly adds wacky spacing.

**Comment by blerner** [comment]
You should use both top and bottom, so that the first and last lines are symmetric. You should probably use 0.1em instead of ###px, so it scales when we resize fonts.

**Comment by blerner** [comment]
And you should use whatever border width is equal to the line spacing that CM uses. (Joe's probably getting it to work with 1px because two of them just touch, and having larger borders is ok because of CSS border collapsing.)

**Comment by jpolitz** [comment]
The partial boxes confused me because they appear to curve around the keyword, making it look like an incomplete rounded box (to my eye).

Doing it without a border-radius (so square edges) fixes this visual glitch for me.

**Comment by blerner** [comment]
You can add a border radius only to one corner, so that should help too...

**Comment by jpolitz** [comment]
Ah, good point.  So `border-top-left-radius` and `border-bottom-right-radius` for the start and end, respectively.

**Comment by jswrenn** [comment]
@blerner changes fix the issue of code being obscured by the fuzziness but still succeeds in being visually distinct from highlights.

**Comment by jpolitz** [comment]
This looks awesome.
