### ISSUE TITLE
Keyword Matching JS Error on Colon

### ISSUE THREAD

**Issue by belph** [brownplt/code.pyret.org#69]
Putting the cursor after (for example) the colon in `ask:` causes the following error in the JS console:

```
Error: Invalid Starting Token: [object Object]
```

Note that this doesn't have any other adverse effects beyond not highlighting the colon and producing the error message (i.e. the highlighting still works after the error is triggered)

**Comment by belph** [comment]
Closing, since after the latest matcher tweaks, this is no longer reproducible.

**Comment by belph** [comment]
This issue has re-manifested on `sql`. I'm probably doing something in `pyret-fold` which is too delicate in terms of the starting token (and there's probably some implicit invariant that's getting violated).

**Comment by blerner** [comment]
Did you diff pyret-fold and pyret-mode from #horizon to #sql?  Good bet that a token isn't getting set with a type, correctly.  You might also want to merge horizon into sql, to make sure any changes/fixes there have been incorporated...

**Comment by belph** [comment]
I'm currently in the process of going through the changes in `pyret-mode` (`pyret-fold` has no `sql`-created changes). You're guess is probably correct.

**Comment by blerner** [comment]
Also check any changes I made on #new-horizons, too; I think that's where I tweaked the support for `block` shorthand, and fixed a few things.

**Comment by belph** [comment]
Traced the problem to a typo in `pyret-mode.js`: https://github.com/brownplt/code.pyret.org/blob/1f17387cfb5214bb2d02e3aca032092881660a3c/src/web/js/codemirror/pyret-mode.js#L409

This fixes it, so I'm re-closing.
