### ISSUE TITLE
Syntax highlighting disappears after running check block

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/code.pyret.org#70]
In horizon, after running a check block, the program's syntax highlighting goes away, and the program becomes uniformly black.

This does not happen in master.

**Comment by blerner** [comment]
Known issue -- seems to have been a deliberate change in the CSS: https://github.com/brownplt/code.pyret.org/blame/64ea981603f1de85f423e08a1e5b67d7e17c0831/src/web/css/editor.css#L842 

@jswrenn : what was your design here, in using `!important`?

(Also https://github.com/brownplt/code.pyret.org/issues/65#issuecomment-218951227)
