### ISSUE TITLE
`satisfies` can break when the predicate throws an exception

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#71]
```
check:
  fun failure(val): raise("nope") end
  
  5 satisfies failure
end
```
This causes rendering errors in CPO.

**Comment by jpolitz** [comment]
These should be marked `horizon-fixed`, not closed.

**Comment by jpolitz** [comment]
Also, another place for an automated test.

**Comment by jswrenn** [comment]
@jpolitz Is `horizon-fixed` applicable even when the bug never appeared on `master`?

**Comment by jpolitz** [comment]
Yeah, this label is for things to close when we merge (which should happen very soon).
