### ISSUE TITLE
Big-bang does not check that to-draw returns an image

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#75]
This program: 

`big-bang(0, [list: to-draw(lam(w): 55 end)])`

Produces the following error:

<img width="614" alt="screen shot 2016-05-24 at 10 13 56 pm" src="https://cloud.githubusercontent.com/assets/119891/15526037/de4c9b38-21fc-11e6-8890-0ee11aae26f0.png">

**Comment by sorawee** [comment]
Isn't this the same as #53?

**Comment by jpolitz** [comment]
Yup
