### ISSUE TITLE
Another common error needs a better message

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#79]
From a thread with @jswrenn @jpolitz @shriram and @blerner -- We should shorten the "Pyret didn’t understand your program around..." error, so that there's no need for the `(more...)` link. IIRC, we settled on the following:

`You may need to add or remove some text to fix your program. Look carefully before the highlighted text. Is there a missing colon (:), comma (,), string marker ("), or keyword? Is there something there that shouldn’t be?`

**Comment by jpolitz** [comment]
Any disagreement, others?  None from me.

**Comment by blerner** [comment]
https://github.com/brownplt/pyret-lang/commit/10e62c9c93da0f38699f1f873da0beab38713cba

**Comment by blerner** [comment]
Drat, that didn't work for some reason; hang on, fix coming

**Comment by blerner** [comment]
better
