### ISSUE TITLE
"Darkening" is wrong in errors

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#84]
```
data Foo:
| foo(x:: Number)
end
cases(Foo) foo:
  | foo(_) => 5
end
```
Run, then click `Show program trace`, and mouseover the line shown.  The entire screen goes dark, except the error block itself; no code is highlighted.

**Comment by jswrenn** [comment]
Closed by 9491023fff201ce17b0fd515aea778190006bb2a.
