### ISSUE TITLE
Errors when using invalid identifiers

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#90]
Reported by @kfisler  
If the user tries to evaluate `class`, they get the following error:
```Well-formedness: Pyret disallows the use of class as an identifier``` 

I wonder if we can do better? Perhaps:
```class : this is part of the language, and cannot be used as an identifier```

**Comment by jpolitz** [comment]
What's the underlying problem with the first one?  That `well-formedness` is vague, maybe?  Just trying to understand the issue.

`class` isn't part of the language, so the proposed message isn't quite there.  Maybe someday it will.  We just did a big land-grab on future reserved words early on.

How about:

The name `class` is reserved by Pyret, and cannot be used as an identifier

**Comment by schanzer** [comment]
Your proposed revision LGTM. @kfisler ?

**Comment by kfisler** [comment]
LGTM
