### ISSUE TITLE
Publish button sometimes seems unresponsive

### ISSUE THREAD

**Issue by kfisler** [brownplt/code.pyret.org#95]
Yesterday, I had four programs that I wanted to publish.  For one of them, pressing publish yielded a response fairly quickly.  For the others, I got the message about gathering sharing data, but a few minutes later that message was still all that was showing.  I seem to recall I had to hit publish several times (waiting a couple of minutes between tries) before I actually got to the ability to generate a new link.

**Comment by schanzer** [comment]
@kfisler are you still seeing this periodically? If not, OK to close?

**Comment by kfisler** [comment]
I haven't looked in ages. Let's close for now
