### ISSUE TITLE
Clearing highlight only works on the first highlight/edit cycle

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#96]
Run this program:

```
fun move-character(obj, key):

  ask:
    | key == "left" then: { x: obj.x - 1, y: obj.y }
    | key == "right" then: { x: obj.x + 1, y: obj.y }
  end

  ask:
    | key == "up" then: { x: obj.x, y: obj.y + 1 }
    | key == "down" then: { x: obj.x, y: obj.y - 1 }  
  end

end
```

You get the expected error for multiple expressions in a block.

If you add some newlines between the `ask` blocks, the highlight clears.  If you _re_-highlight by clicking the error, then the block rehighlights, but further edits don't clear the highlight.

**Comment by blerner** [comment]
This seems not to be the behavior any more: clicking within the highlights removes them.  Confirm and close?

**Comment by schanzer** [comment]
None of the behavior in OP is no longer accurate: 
1. Adding newlines does _not_ clear the highlight. 
2. Re-highlighting does not change editing behavior

OK to close?
