### ISSUE TITLE
Ask for permissions as needed, rather than up front

### ISSUE THREAD

**Issue by jpolitz** [brownplt/code.pyret.org#99]
CPO asks for a lot of permissions, and it justifiably irks folks:

https://twitter.com/yminsky/status/756459297077399552

Would be good to see if we can get down to a minimal set initially (say, "View files created by this app" and "See my email", and maybe "Add to Drive"), and then only add photos/sheets on-demand or as asked by user.

For photos, we have a natural moment to do it with the Picker API.  For sheets, we could see if there's a way to do it naturally with a sheet choosing API as the way to get started with sheets, as well.

There are backend details about remembering which scopes a user has requested and using the right ones to refresh access tokens, etc, but worth seeing how annoying this would be.

**Comment by sorawee** [comment]
Is this closable, now that we don't ask for that many permissions?

**Comment by jpolitz** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉
